def Cube():
  set_safety_mode_transition_hardness(1)
  step_count_539ef0ac_7472_4f69_9b5e_36b360dcef6c = 0.0
  thread Step_Counter_Thread_9ad19105_0a3b_41b9_a484_428244ae2445():
    while (True):
      step_count_539ef0ac_7472_4f69_9b5e_36b360dcef6c = step_count_539ef0ac_7472_4f69_9b5e_36b360dcef6c + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_9ad19105_0a3b_41b9_a484_428244ae2445()
  set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
  set_standard_analog_input_domain(0, 0)
  set_standard_analog_input_domain(1, 0)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 1)
  set_analog_outputdomain(1, 1)
  set_input_actions_to_default()
  set_runstate_standard_digital_outputs([3])
  set_runstate_standard_digital_output_to_value(3, 1)
  set_gravity([0.0, 0.0, 9.82])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  set_target_payload(3.020000, [0.012000, 0.022000, 0.058000], [0.009713, 0.009713, 0.009713, 0.000000, 0.000000, 0.000000])
  global CubeFront=p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902]
  # begin: URCap Installation Node
  #   Source: Aruna Vision, 1.2.5.ALPHA, Aruna Robotics
  #   Type: Aruna Vision by 3D Infotech
  daemon_cam_swing = rpc_factory("xmlrpc", "http://127.0.0.1:40407/RPC2")
  isInitConstruct = daemon_cam_swing.InitConstruct(5)
  if isInitConstruct:
  sleep(0.2)
  end
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
  #   Type: Copilot
  ###############################################################
  # Script file used to communicate with Robotiq's ft sensor
  # Version: 0.0.1
  ###############################################################

  node_rpc_server = rpc_factory("xmlrpc","http://127.0.0.1:4251/node")
  linalg = rpc_factory("xmlrpc","http://127.0.0.1:4251/linalg")
  storevar = rpc_factory("xmlrpc","http://127.0.0.1:4251/storevariable")
  kinematics_rpc_server = rpc_factory("xmlrpc","http://127.0.0.1:4251/")

  global Fx = 0.0
  global Fy = 0.0
  global Fz = 0.0
  global Mx = 0.0
  global My = 0.0
  global Mz = 0.0
  global T_base_sensor = p[0,0,0,0,0,0]
  global tcp_wrench = [0,0,0,0,0,0]
  global base_wrench = [0,0,0,0,0,0]
  global rq_target_joint_positions = get_actual_joint_positions()
  global rq_linear_axis_move_abs_target_position = 0.0
  global rq_linear_axis_move_abs_target_speed = 0.0
  global rq_linear_axis_move_abs_target_acc = 0.0
  global rq_linear_axis_move_abs_target_decel = 0.0
  global rq_linear_axis_move_absolute_thread = 0
  global rq_linear_axis_move_absolute_thread_running = False
  global rq_ft_sensor_connected = False
  global rq_active_node = 0
  global rq_elapsed_time = 0
  rq_force_protect_urcap = 0.0
  rq_torque_protect_urcap = 0.0
  rq_collision_detection_enabled = False
  rq_collision_detection_active_time = 0.0
  rq_halt_on_collision_detection = True
  sensor_wrench = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  rq_node_executor_thread_running = False
  rq_lookahead_time = 0.05
  rq_continue_node_execution = True

  rq_controller_time_step = 0.008

  def pose_to_list(p):
    return [p[0], p[1], p[2], p[3], p[4], p[5]]
  end

  def rq_init_path(pathId):
     initPathAnswer = node_rpc_server.initpath(pathId)
     verify_path_answer(initPathAnswer)
     return initPathAnswer[0]
  end

  def linear_axis_move_abs(target_position,
                           target_speed,
                           target_acceleration,
                           target_deceleration,
                           is_blocking):
    rq_linear_axis_move_abs_target_position = target_position
    rq_linear_axis_move_abs_target_speed = target_speed
    rq_linear_axis_move_abs_target_acc = target_acceleration
    rq_linear_axis_move_abs_target_decel = target_deceleration

    if( rq_linear_axis_move_absolute_thread_running ):
      kill rq_linear_axis_move_absolute_thread
    end
    rq_linear_axis_move_absolute_thread = run linear_axis_move_abs_thread()
    if(is_blocking):
      join rq_linear_axis_move_absolute_thread
    end
  end #linear_axis_move_abs

  thread linear_axis_move_abs_thread():
    rq_linear_axis_move_absolute_thread_running = True
    timeout_in_milliseconds = 500
    target_position_reached = False
    number_of_done_status_received_while_not_at_target = 0

    while( not target_position_reached ):
      move_absolute_response = node_rpc_server.linearaxismove(rq_linear_axis_move_abs_target_position,
                                                        rq_linear_axis_move_abs_target_speed,
                                                        rq_linear_axis_move_abs_target_acc,
                                                        rq_linear_axis_move_abs_target_decel,
                                                        timeout_in_milliseconds)

      if move_absolute_response == 0: # Done
        position_tolerance = 1e-3
        local position = node_rpc_server.linearaxisgetactualposition() # local because it is a variable under 15 chars that a user could have defined
        target_position_reached = ( norm( position - rq_linear_axis_move_abs_target_position ) < position_tolerance )
        if not target_position_reached:
          number_of_done_status_received_while_not_at_target = number_of_done_status_received_while_not_at_target + 1
          if ( number_of_done_status_received_while_not_at_target > 10 ): #When the move starts, it may take some time before the status changes from done to busy so we accept a certain number of done status without being at the target position
            textmsg("error: target position should be reached when move absolute status is Done")
          end
        end
      elif move_absolute_response == 1: # Normal (safeguard stopped, busy moving, or paused)
        # do nothing
      elif move_absolute_response == 2: # Error
        textmsg("Linear axis absolute move error")
        popup("Program paused because axis is not ready or the requested position is outside the allowed range.",
              title="Linear axis move error", warning=False, error=True, blocking=True)
        socket_send_line("pause", "RQDashboardClient") # If the axis is not ready, this allows the user to go fix it and then resume the program.
        sleep(1.0) # The socket_send_line command is non-blocking, so we need to wait for the progam to pause.
                   # Without the sleep, execution will continue and multiple popups and program pauses will be executed.
      end

      sleep(0.008)
    end #while
    rq_linear_axis_move_absolute_thread_running = False
  end # linear_axis_move_abs_thread

  def setup_force_node_on_server(generic_rq_insertion_force_node_id = 1,
                                 feature=1,
                                 targetforce = [0,0,0,0,0,0],
                                 force_control_enabled_axes = [False, False, False, False, False, False],
                                 max_negative_deviation_vector = [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
                                 max_positive_deviation_vector = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                                 adaptiveStiffness = True):
    node_rpc_server.setforcecontrolfeature(generic_rq_insertion_force_node_id, feature)
    node_rpc_server.setforcecontroltargetforce(generic_rq_insertion_force_node_id, targetforce)
    node_rpc_server.setforcecontrolenabledaxes(generic_rq_insertion_force_node_id, force_control_enabled_axes)
    node_rpc_server.setforcecontrolmaximaldeviation(generic_rq_insertion_force_node_id, max_negative_deviation_vector, max_positive_deviation_vector)
    node_rpc_server.setforcecontroladaptivestiffnessenabledaxes(generic_rq_insertion_force_node_id, True)
  end

  def verify_path_answer(path_answer):
   initPathStatusCode = path_answer[1]
   handle_path_node_error_code(initPathStatusCode)
  end

  def handle_path_node_error_code(initPathStatusCode):
    if initPathStatusCode == -1:
      popup("Could not compute path with the selected options.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 1:
      popup("Joint solution impossible. Change your starting position.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 2:
      popup("Discontinuous path detected. Change your starting position.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 3:
      popup("Path time limit has been reached. Increase the speed of your path or break it down in multiple shorter paths.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 4:
      popup("Could not compute path with the selected options. Computing path timeout.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 5:
      popup("Path computation was aborted.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 6:
      popup("A previous path computation is still in progress. Please try again in a few seconds.", "Robotiq's FT Sensor", blocking=True, error=True)
    elif initPathStatusCode == 7:
      textmsg("Path initialization error: Invalid path id.") # No popup needed in this case.
    elif initPathStatusCode == 8:
      popup("Palletizer error: box number out of range.", blocking=True, error=True)
    elif initPathStatusCode == 9:
      popup("Palletizer error: collision detected.", blocking=True, error=True)
    elif initPathStatusCode == 10:
      popup("Palletizer error: boxes overlap in layer.", blocking=True, error=True)
    elif initPathStatusCode == 11:
      popup("Palletizer error: empty layer.", blocking=True, error=True)
    elif initPathStatusCode != 0:
      textmsg("Unexpected initPathStatusCode value : ", initPathStatusCode)
    end

    if initPathStatusCode != 0:
      halt
    end
  end


  def rq_wait_ft_sensor_steady(timeout = 2000):

    max_mean_squared_error = [0.1, 0.1, 0.1, 0.0001, 0.0001, 0.0001]
    mean = sensor_wrench

    mean_squared_error = sensor_wrench
    i=0
    while i<6:
      mean_squared_error[i] = mean_squared_error[i] * mean_squared_error[i]
      i=i+1
    end

    is_sensor_steady = False
    alpha = 0.9
    timer = 0

    while (not is_sensor_steady) and (timer < timeout):
      sleep(rq_controller_time_step)
      timer = timer + 8

      i = 0
      while i < 6:
        mean[i] = alpha * mean[i] + (1.0 - alpha) * sensor_wrench[i]
        error = sensor_wrench[i] - mean[i]
        mean_squared_error[i] = alpha * mean_squared_error[i] + ((1.0 - alpha) * error * error)
        i = i+1
      end

      is_sensor_steady = True
      i = 0
      while (i < 6) and is_sensor_steady:
        is_sensor_steady = mean_squared_error[i] < max_mean_squared_error[i]
        i = i+1
      end
    end

    return is_sensor_steady
  end

  thread rq_elapsed_timer_ms():
    rq_elapsed_time = 0
  dt = 1000/500
    while True:
      rq_elapsed_time =  rq_elapsed_time + dt
      sync()
    end
  end

  def get_sensor_fx():
    return Fx
  end

  def get_sensor_fy():
    return Fy
  end

  def get_sensor_fz():
    return Fz
  end

  def get_sensor_mx():
    return Mx
  end

  def get_sensor_my():
    return My
  end

  def get_sensor_mz():
    return Mz
  end

  def get_applied_tcp_force(index):
    return -1.0 * tcp_wrench[index]
  end

  def get_applied_base_force(index):
    return -1.0 * base_wrench[index]
  end

  def express_vector_in_new_frame(T_from_to, V_from):
    Q_from_to = p[0, 0, 0, T_from_to[3], T_from_to[4], T_from_to[5]]
    V_to = pose_trans(pose_inv(Q_from_to), p[V_from[0], V_from[1], V_from[2], 0, 0, 0])
    return [V_to[0], V_to[1], V_to[2]]
  end

  def express_force_in_frame(T_from_to, wrench_from):
    F = express_vector_in_new_frame(T_from_to, [wrench_from[0], wrench_from[1], wrench_from[2]])
    T = express_vector_in_new_frame(T_from_to, [wrench_from[3], wrench_from[4], wrench_from[5]])
    return [F[0], F[1], F[2], T[0], T[1], T[2]]
  end

  thread read_force():


    if (not socket_open("127.0.0.1", 29999, "RQDashboardClient")):
      popup("Can't connect to the Dashboard server", "Robotiq's FT Sensor", error=True)
      halt
    end

    rq_collision_detection_active_count = 0
    rq_collision_detection_active = False

    while True:

        T_base_tcp = get_actual_tcp_pose()
        T_base_flange = get_actual_tool_flange_pose()
        T_flange_sensor = p[0, 0, 0, 0, 0, 0]
        T_base_sensor = pose_trans(T_base_flange, T_flange_sensor)

        T_flange_tcp = pose_trans( pose_inv(T_base_flange), T_base_tcp)
        T_sensor_tcp = pose_trans( pose_inv(T_flange_sensor), T_flange_tcp)

        sensor_wrench = express_force_in_frame(T_base_sensor, get_tcp_force())
        tcp_wrench = wrench_trans(pose_inv(T_sensor_tcp), sensor_wrench)
        base_wrench = express_force_in_frame(pose_inv(T_base_tcp), tcp_wrench)

        Fx = sensor_wrench[0]
        Fy = sensor_wrench[1]
        Fz = sensor_wrench[2]
        Mx = sensor_wrench[3]
        My = sensor_wrench[4]
        Mz = sensor_wrench[5]

        write_output_float_register(TCP_FX_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[0])
        write_output_float_register(TCP_FY_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[1])
        write_output_float_register(TCP_FZ_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[2])
        write_output_float_register(TCP_MX_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[3])
        write_output_float_register(TCP_MY_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[4])
        write_output_float_register(TCP_MZ_ACTUAL_OUTPUT_DOUBLE, tcp_wrench[5])

        if rq_collision_detection_enabled:
            if rq_collision_detection_active_time < (0.5*rq_controller_time_step):
                if norm([Fx, Fy, Fz]) > rq_force_protect_urcap:
                    rq_on_collision_detection("Force limit value exceeded.")
                elif norm([Mx, My, Mz]) > rq_torque_protect_urcap:
                    rq_on_collision_detection("Torque limit value exceeded.")
                end
            else:
                rq_collision_detection_active_time = rq_collision_detection_active_time + rq_controller_time_step
                if rq_collision_detection_active_time >= 1.0:
                    rq_collision_detection_active_time = 0.0
                end
            end
        end

        sync()
        sync()
        sync()
        sync()

    end
  end

  def rq_get_ft_sensor_state():
    socket_open("127.0.0.1",63350,"rq_ft_sensor_state")
    socket_send_string("CURRENT STATE", "rq_ft_sensor_state")
    rq_sensor_state = socket_read_string("rq_ft_sensor_state")
    socket_close("rq_ft_sensor_state")

    if rq_sensor_state == "":
      rq_sensor_state = "RQ_STATE_INIT"
    end

    return rq_sensor_state
  end

  def rq_ft_sensor_disconnected_warn_user():
    socket_open("127.0.0.1",29999,"SensorWarning")
    socket_send_string("popup FT Sensor must be connected to run this program.","SensorWarning")
    socket_send_byte(10,"SensorWarning")
    socket_close("SensorWarning")
  end

  def rq_ft_sensor_disconnected_stop_program():
    socket_open("127.0.0.1", 30002, "rq_ft_sensor_stop_socket")

    socket_send_string("def rq_ft_sensor_stop_program():", "rq_ft_sensor_stop_socket")
    socket_send_byte(10, "rq_ft_sensor_stop_socket")
    socket_send_string("  stopj(5.0)", "rq_ft_sensor_stop_socket")
    socket_send_byte(10, "rq_ft_sensor_stop_socket")
    socket_send_string("end", "rq_ft_sensor_stop_socket")
    socket_send_byte(10, "rq_ft_sensor_stop_socket")

    socket_close("rq_ft_sensor_stop_socket")
  end

  def rq_ft_sensor_disconnected_check():
    if rq_get_ft_sensor_state() == "RQ_STATE_INIT":
      rq_ft_sensor_disconnected_stop_program()
      rq_ft_sensor_disconnected_warn_user()

      return True
    else:
      return False
    end
  end

  #RTDE input registers
  TARGET_JOINT_0_INPUT_REGISTER_DOUBLE = 40
  TARGET_JOINT_1_INPUT_REGISTER_DOUBLE = 41
  TARGET_JOINT_2_INPUT_REGISTER_DOUBLE = 42
  TARGET_JOINT_3_INPUT_REGISTER_DOUBLE = 43
  TARGET_JOINT_4_INPUT_REGISTER_DOUBLE = 44
  TARGET_JOINT_5_INPUT_REGISTER_DOUBLE = 45
  FINISH_NODE_INPUT_REGISTER_INT32 = 40
  RUNTIME_ERROR_INPUT_REGISTER_INT32 = 41
  ACTIVATION_NODE_COUNT_INPUT_REGISTER_INT32 = 42

  #RTDE output registers
  ACTIVE_NODE_OUTPUT_REGISTER_INT32 = 40
  NODE_EXECUTION_OUTPUT_COUNT_INT32 = 41
  ACTIVATION_NODE_COUNT_OUTPUT_REGISTER_INT32 = 42
  TCP_FX_ACTUAL_OUTPUT_DOUBLE = 34
  TCP_FY_ACTUAL_OUTPUT_DOUBLE = 35
  TCP_FZ_ACTUAL_OUTPUT_DOUBLE = 36
  TCP_MX_ACTUAL_OUTPUT_DOUBLE = 37
  TCP_MY_ACTUAL_OUTPUT_DOUBLE = 38
  TCP_MZ_ACTUAL_OUTPUT_DOUBLE = 39
  GENERAL_OUTPUT_DOUBLE_40 = 40
  GENERAL_OUTPUT_DOUBLE_41 = 41
  GENERAL_OUTPUT_DOUBLE_42 = 42
  GENERAL_OUTPUT_DOUBLE_43 = 43
  GENERAL_OUTPUT_DOUBLE_44 = 44
  GENERAL_OUTPUT_DOUBLE_45 = 45

  write_output_integer_register(ACTIVE_NODE_OUTPUT_REGISTER_INT32, 0)
  write_output_integer_register(NODE_EXECUTION_OUTPUT_COUNT_INT32, 0)
  write_output_integer_register(ACTIVATION_NODE_COUNT_OUTPUT_REGISTER_INT32, 0)
  write_output_float_register(TCP_FX_ACTUAL_OUTPUT_DOUBLE, 0)
  write_output_float_register(TCP_FY_ACTUAL_OUTPUT_DOUBLE, 0)
  write_output_float_register(TCP_FZ_ACTUAL_OUTPUT_DOUBLE, 0)
  write_output_float_register(TCP_MX_ACTUAL_OUTPUT_DOUBLE, 0)
  write_output_float_register(TCP_MY_ACTUAL_OUTPUT_DOUBLE, 0)
  write_output_float_register(TCP_MZ_ACTUAL_OUTPUT_DOUBLE, 0)

  global activation_node_count = 0
  global node_execution_count = 0

  def element_wise_subtract(l1, l2):
    global r = l1
    i=0
    while i<length(r):
      r[i]=l1[i]-l2[i]
      i=i+1
    end
    return r
  end

  def element_wise_add(l1, l2):
    result = l1
    i = 0
    while i < length(result):
      result[i] = l1[i] + l2[i]
      i = i + 1
    end
    return result
  end

  def list_by_scalar_multiply(l1, scalar):
      global r = l1
      i=0
      while i<length(r):
        r[i]=l1[i]*scalar
        i=i+1
      end
      return r
   end

  def norm_inf(v):
    norm = 0
    i=0
    while i<length(v):
        n = norm(v[i])
        if(n > norm):
          norm = n
        end
      i=i+1
    end
    return norm
  end

  def active_and_reset_node(nodeId):
    server_activation_node_count = read_input_integer_register(ACTIVATION_NODE_COUNT_INPUT_REGISTER_INT32)

    activation_node_count = activation_node_count + 1
    node_execution_count = 0
    write_output_integer_register(NODE_EXECUTION_OUTPUT_COUNT_INT32, node_execution_count)
    rq_active_node = nodeId
    write_output_integer_register(ACTIVE_NODE_OUTPUT_REGISTER_INT32, nodeId)
    write_output_integer_register(ACTIVATION_NODE_COUNT_OUTPUT_REGISTER_INT32, activation_node_count)

    while server_activation_node_count == read_input_integer_register(ACTIVATION_NODE_COUNT_INPUT_REGISTER_INT32):
      sleep(rq_controller_time_step)
    end
  end

  def execute_node(nodeId, startThread = False):
    node_execution_thread = 0
    active_and_reset_node(nodeId)
    if startThread:
      rq_target_joint_positions = get_actual_joint_positions()
      movej(rq_target_joint_positions) # This movej is used to prevent the "another thread is already controlling the robot" error.
      rq_continue_node_execution = True
      node_execution_thread = run execute_node_thread()
    end
    while not active_node_completed():
      sync()
    end
    return node_execution_thread
  end

  def setup_node_execution_related_variables():
    activation_node_count = 0
    node_execution_count = 0
    write_output_integer_register(ACTIVE_NODE_OUTPUT_REGISTER_INT32, 0)
    write_output_integer_register(ACTIVATION_NODE_COUNT_OUTPUT_REGISTER_INT32, activation_node_count)
    write_output_integer_register(NODE_EXECUTION_OUTPUT_COUNT_INT32, node_execution_count)
    sleep(rq_controller_time_step)
  end

  def start_node_executor():
    setup_node_execution_related_variables()

    succeeded = node_rpc_server.startnodeexecutor()
    if not succeeded:
      node_rpc_server.stopnodeexecutor()
      sleep(0.5) # Needed for URControl to free the input registers.
      succeeded = node_rpc_server.startnodeexecutor()
      if not succeeded:
        popup("RTDE interface cannot initialize. Make sure that Ethernet/IP adapter and Profinet are disabled, and that no other URCaps use the RTDE interface.", "Robotiq Copilot", error=True)
        halt
      end
    end

    hand_shake_xmlrpcserver()
  end

  def reset_node_executor():
    setup_node_execution_related_variables()

    succeeded = node_rpc_server.resetnodeexecutor()
    if not succeeded:
      popup("RTDE interface cannot initialize. Make sure that Ethernet/IP adapter and Profinet are disabled, and that no other URCaps use the RTDE interface.", "Robotiq Copilot", error=True)
      halt
    end

    hand_shake_xmlrpcserver()
  end

  def hand_shake_xmlrpcserver():
    timer_thread = run rq_elapsed_timer_ms()
    sleep(rq_controller_time_step)
    node_execution_initialized = False
    while (not node_execution_initialized) and (rq_elapsed_time < 100):
      node_execution_initialized = (read_input_integer_register(FINISH_NODE_INPUT_REGISTER_INT32) == -1)
      sleep(rq_controller_time_step)
    end
    kill timer_thread

    if (not node_execution_initialized):
      popup("Node Execution initialization failed.", "Robotiq Copilot", error=True)
      halt
    end
  end

  thread execute_node_thread():
    rq_target_joint_positions = get_actual_joint_positions()
    servoj(rq_target_joint_positions)
    while rq_continue_node_execution:
      new_rq_target_joint_positions = update_target_position()
      joint_target_distances = element_wise_subtract(new_rq_target_joint_positions, rq_target_joint_positions)
      max_joint_target_displacement = norm_inf(joint_target_distances)
      if max_joint_target_displacement > 0.2:
          textmsg("previous target position: ", rq_target_joint_positions)
          textmsg("next target position: ", new_rq_target_joint_positions)
          textmsg("max joint target displacement: ", max_joint_target_displacement)
          popup("Node executor error: see Log tab for details", "Robotiq Copilot", False, True, True)
          halt
      end

      i = 1
      while i < 5: # (servoj frequency)/(rtde frequency) = 500/125 = 4
        rq_target_joint_positions_interpolated = element_wise_add( rq_target_joint_positions,
                                                                   list_by_scalar_multiply(joint_target_distances, 0.25*i) )
        servoj(rq_target_joint_positions_interpolated, t=get_steptime(), lookahead_time=rq_lookahead_time, gain=500)
        i = i + 1
      end

      rq_target_joint_positions = new_rq_target_joint_positions
    end
    stopj(5)
  end

  # The thread below is used to prevent "another thread is already controlling the robot error".
  # In some occasions, even a sleep(0.05) will not work so this is necessary (until fixed by UR).
  # The thread is immediately killed to avoid unnecessary motion for the case of a parent node
  # that modifies the servoj target joint positions.
  def kill_thread( thread_id ):
    kill thread_id
    run_movej_thread = run movej_thread()
    sleep(rq_controller_time_step)
    kill run_movej_thread
  end

  thread movej_thread():
    movej(rq_target_joint_positions)
  end

  def active_node_completed():
    return (read_input_integer_register(ACTIVATION_NODE_COUNT_INPUT_REGISTER_INT32) == activation_node_count) and
           (read_input_integer_register(FINISH_NODE_INPUT_REGISTER_INT32) == rq_active_node)
  end

  def rq_handle_error_code(code):
    message = "Runtime error!"

    if code == 1:
      message = "Robotiq license error!"
    elif code == 2:
      message = "Program stopped due to runtime error. Please restart the program."
    end

    popup(message, "Robotiq Copilot", error=True)
    halt
  end

  def update_target_position():

    error_code = read_input_integer_register(RUNTIME_ERROR_INPUT_REGISTER_INT32)

    if error_code != 0:
      rq_handle_error_code(error_code)
    end

    new_rq_target_joint_positions = [0,0,0,0,0,0]
    new_rq_target_joint_positions[0] = read_input_float_register(TARGET_JOINT_0_INPUT_REGISTER_DOUBLE)
    new_rq_target_joint_positions[1] = read_input_float_register(TARGET_JOINT_1_INPUT_REGISTER_DOUBLE)
    new_rq_target_joint_positions[2] = read_input_float_register(TARGET_JOINT_2_INPUT_REGISTER_DOUBLE)
    new_rq_target_joint_positions[3] = read_input_float_register(TARGET_JOINT_3_INPUT_REGISTER_DOUBLE)
    new_rq_target_joint_positions[4] = read_input_float_register(TARGET_JOINT_4_INPUT_REGISTER_DOUBLE)
    new_rq_target_joint_positions[5] = read_input_float_register(TARGET_JOINT_5_INPUT_REGISTER_DOUBLE)

    node_execution_count = node_execution_count + 1
    write_output_integer_register(NODE_EXECUTION_OUTPUT_COUNT_INT32, node_execution_count)
    return new_rq_target_joint_positions
  end

  def set_servoj_node_cmd(q):
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_40, q[0])
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_41, q[1])
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_42, q[2])
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_43, q[3])
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_44, q[4])
    write_output_float_register(GENERAL_OUTPUT_DOUBLE_45, q[5])
  end

  def rq_collision_detection_start(force_limit = 140, torque_limit = 14, halt_on_collision = True):
    rq_force_protect_urcap = force_limit
    rq_torque_protect_urcap = torque_limit
    rq_collision_detection_active_time = 0.0
    rq_collision_detection_enabled = True
    rq_halt_on_collision_detection = halt_on_collision
  end

  def rq_collision_detection_stop():
    rq_collision_detection_enabled = False
  end

  def rq_on_collision_detection(message):
    textmsg("Collision Detection. " + message)
    popupTitle = "Collision Detection"
    if rq_halt_on_collision_detection:
      popup(message + " Program halt.", popupTitle, False, True, False)
      halt
    else:
      popup(message + " Program suspend.", popupTitle, True, False, False)
      socket_send_line("pause", "RQDashboardClient")
      rq_collision_detection_active_time = rq_controller_time_step
    end
  end

  def round(number_to_round):
    if number_to_round - floor(number_to_round) < 0.5:
      return floor(number_to_round)
    else:
      return ceil(number_to_round)
    end
  end

  def rq_execute_box_trajectory(nodeId, current_box_count, has_box_payload, end_pose_offset = p[0,0,0,0,0,0]):
    payload_mass = get_target_payload()
    payload_cog  = get_target_payload_cog()
    flange_payload = [payload_mass, payload_cog[0], payload_cog[1], payload_cog[2]]

    path_answer = node_rpc_server.initboxtrajectory(nodeId, current_box_count, has_box_payload, flange_payload, end_pose_offset)

    verify_path_answer(path_answer)
    reset_node_executor()
    node_execution_thread = execute_node(nodeId, True)
    rq_continue_node_execution = False
    join node_execution_thread
  end

  ################################
  # MAIN
  ################################

  run read_force()
  start_node_executor()
  
  preparationErrorXmlRpcClient = rpc_factory("xmlrpc","http://localhost:41547")
  contactOffsetXmlRpcClient = rpc_factory("xmlrpc","http://localhost:40031")
  palletizerXmlRpcClient = rpc_factory("xmlrpc","http://localhost:42239")
    ###############################################################
    # Halt if a script preparation error occurred
    ###############################################################
    def checkForScriptPreparationException():
      if(preparationErrorXmlRpcClient.hasErrorOccurred()):
        popup(preparationErrorXmlRpcClient.getErrorMessage(), title=preparationErrorXmlRpcClient.getNodeInErrorTitle(), error=True, blocking=True)
        halt
      end
    end
  
    checkForScriptPreparationException()
  #***********************************************************************************************
  # verify tap detection
  #***********************************************************************************************
  
  def rq_tap_count(forces, high_threshold):
  
    low_threshold = 2
    tapCount = 0
    lookingForPeak = True
    indexDown = 0
  
    i = 1
    lastIndex = length(forces) - 1
    while i <= lastIndex:
  
      deltaForce = forces[i] - forces[0]
  
     if lookingForPeak:
        if deltaForce >  high_threshold:
          lookingForPeak = False
        end
      else:
        if deltaForce < low_threshold:
          tapCount = tapCount + 1
          lookingForPeak = True
          indexDown = i
        end
      end
      i = i + 1
  
    end
  
    if indexDown != lastIndex:
      tapCount = 0
    end
  
    return tapCount
  
  end
  def shift_right(list, default_value = 0):
  
     i = length(list)-1
     while (i > 0):
        list[i]=list[i-1]
        i=i-1
     end
     list[0] = default_value
  
     return list
  end
  
  #***********************************************************************************************
  # Wait for force reached
  #***********************************************************************************************
  # desired_wrench : desired wrench
  # is_active      : list of 0 and 1, 1 : axis is controlled
  # feature        : 0:base, 1:tcp
  # timeout        : timeout in miliseconds
  #***********************************************************************************************
  def rq_wait_for_force_reached(desired_wrench, is_active, feature, timeout):
  
    feature_base = 0
    feature_tool = 1
    time_constant = 0.025
    alpha = 1 - pow(2.718, -1.0 * rq_controller_time_step / time_constant)
  
    thresholds = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    minimal_thresholds = [1.0, 1.0, 1.0, 0.1, 0.1, 0.1]
  
    applied_wrench = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    filtered_wrench = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
    if (feature == feature_base):
      applied_wrench = list_by_scalar_multiply(base_wrench, -1.0)
    else:
      applied_wrench = list_by_scalar_multiply(tcp_wrench, -1.0)
    end
    filtered_wrench = applied_wrench
  
    i = 0
    while (i < 6):
      if (is_active[i]):
        thresholds[i] = 0.05 * norm(desired_wrench[i])
        if thresholds[i] < minimal_thresholds[i]:
          thresholds[i] = minimal_thresholds[i]
        end
      else:
        thresholds[i] = 10000
      end
      i = i+1
    end
  
   force_reached = False
  
   timer = 0
  
   while ((not force_reached) and (timer < timeout)):
  
      if (feature == feature_base):
         applied_wrench = list_by_scalar_multiply(base_wrench, -1.0)
      else:
         applied_wrench = list_by_scalar_multiply(tcp_wrench, -1.0)
      end
  
      i = 0
      while (i < 6):
        filtered_wrench[i] = (alpha * applied_wrench[i]) + ((1.0 - alpha) * filtered_wrench[i])
        i = i+1
      end
  
      force_reached = True
  
      i = 0
      while ((i < 6) and force_reached):
        error = norm(desired_wrench[i] - filtered_wrench[i])
        if (error > thresholds[i]):
          force_reached = False
        end
        i = i + 1
      end
  
      timer = timer + rq_controller_time_step
  
      sleep(rq_controller_time_step)
  
    end
  
    return force_reached
  end
  #***********************************************************************************************
  # verify click detection
  #***********************************************************************************************
  click_detection_children_ended = False
  
  def rq_click_detection(force_drop_threshold = 10, torque_drop_threshold = 1, force_radio_button_selected = True):
  
    current_norm = 0
    drop_threshold = 0
    norms = [0.0, 0.0, 0.0, 0.0, 0.0]
    click_detected = False
    wrench_indices = [0,0,0]
  
    if(force_radio_button_selected):
      drop_threshold = force_drop_threshold
      wrench_indices = [0,1,2]
    else:
      drop_threshold =torque_drop_threshold
      wrench_indices = [3,4,5]
    end
  
    while ((not click_detection_children_ended) and (not click_detected)):
  
      current_norm = norm([sensor_wrench[wrench_indices[0]], sensor_wrench[wrench_indices[1]], sensor_wrench[wrench_indices[2]]])
  
      norms[4] = norms[3]
      norms[3] = norms[2]
      norms[2] = norms[1]
      norms[1] = norms[0]
      norms[0] = current_norm
  
      avg_norm = (norms[2] + norms[3] + norms[4]) / 3.0
  
      #Check if clicking is detected with force
      norm_drop = avg_norm - current_norm
      if(norm_drop > drop_threshold):
        textmsg("Click detected")
        click_detected=True
      else:
        sleep(rq_controller_time_step)
      end
    end
  
    return click_detected
  end
  ###############################################################
  # Script file used to define Robotiq functions for the Insertion node
  # Version: 0.0.2
  ###############################################################
  
  rq_ins_offset = p[0, 0, 0, 0, 0, 0]
  rq_ins_start_pose = p[0, 0, 0, 0, 0, 0]
  rq_actual_to_destination = p[0, 0, 0, 0, 0, 0]
  rq_ins_destination =p[0, 0, 0, 0, 0, 0]
  rq_ins_speed_setting = 0
  rq_rotation_not_completed = False
  rq_find_bottom_not_completed = False
  rq_spiral_not_completed = False
  
  def ins_actual_force_urcap(direction="X+"):
    axis = str_at(direction, 0)
    if (axis == "x") or (axis == "X"):
      return norm(get_applied_tcp_force(0))
    elif (axis == "y") or (axis == "Y"):
      return norm(get_applied_tcp_force(1))
    elif (axis == "z") or (axis == "Z"):
      return norm(get_applied_tcp_force(2))
    else:
      textmsg("ins_actual_force_urcap, invalid direction ", direction)
    end
  end
  
  def ins_actual_torque_urcap(direction = "Z+"):
    if (direction == "X+") or (direction == "X-") or (direction == "X"):
      return get_applied_tcp_force(3)
    elif (direction == "Y+") or (direction == "Y-") or (direction == "Y"):
      return get_applied_tcp_force(4)
    else:
      return get_applied_tcp_force(5)
    end
  
  end
  
  def square(a):
    return a*a
  end
  
  def update_servoj_node_target(target_joint_pos):
    set_servoj_node_cmd(target_joint_pos)
    sleep(rq_controller_time_step)
  end
  
  def create_all_insertion_nodes():
    global rq_insertion_force_node_id = node_rpc_server.createnewforcenode()
    global rq_insertion_movej_node_id = node_rpc_server.createnewmovejnode()
    global rq_insertion_servoj_node_id = node_rpc_server.createnewservojnode()
    node_rpc_server.setparentid(rq_insertion_movej_node_id, rq_insertion_force_node_id)
    node_rpc_server.setparentid(rq_insertion_servoj_node_id, rq_insertion_force_node_id)
  end
  
  def get_offset_projected_in_spiral_plane(direction, current_pose, pose_ref):
    axis = str_at(direction, 0)
    axis_index = 0
    if axis == "X":
      axis_index = 0
    elif axis == "Y":
      axis_index = 1
    elif axis == "Z":
      axis_index = 2
    else:
      textmsg("get_offset_projected_in_spiral_plane, invalid direction ", direction)
    end
  
    pose_offset = pose_trans( pose_inv(pose_ref), current_pose ) # current_pose and pose_ref should have the same orientations.
                                                                 # pose_offset is returned expressed in pose_ref frame
  
    pose_offset[axis_index] = 0 # valeur en direction mise a zero
    pose_offset[3] = 0 # valeur en Rx mise a zero
    pose_offset[4] = 0 # valeur en Ry mise a zero
    pose_offset[5] = 0 # valeur en Rz mise a zero
  
    return pose_offset
  end
  
  def update_spiral_offset(direction, spiral_initial_pose, spiral_initial_pose_offset, spiral_initial_pose_offset_name):
    pos_diff_tcp = get_offset_projected_in_spiral_plane(direction, get_actual_tcp_pose(), spiral_initial_pose)
    spiral_initial_pose_offset = interpolate_pose(spiral_initial_pose_offset, pos_diff_tcp, 0.35)
    storevar.setvariablepose(spiral_initial_pose_offset_name, spiral_initial_pose_offset)
  end
  
  def determine_max_spiral_radius_from_actual_position(direction, spiral_initial_pose, max_radius):
      dist_to_initial_pose = norm( get_offset_projected_in_spiral_plane(direction, get_actual_tcp_pose(), spiral_initial_pose))
      if (max_radius > dist_to_initial_pose):
        new_max_radius = max_radius - dist_to_initial_pose
      else:
        new_max_radius = 0
      end
  
      return new_max_radius
  end
  
  def insertion_compliant_move_urcap(axis = "Z",
                                     direction_sign = 1,
                                     compliant_insert_force_threshold = 20,
                                     speed = 0.04,
                                     feature = 1,
                                     max_position_deviation = 0.1):
    feature_base = 0
    feature_tool = 1
  
    if axis == "X":
      axis_index = 0
    elif axis == "Y":
      axis_index = 1
    elif axis == "Z":
      axis_index = 2
    else:
      textmsg("insertion_compliant_move_urcap, invalid direction ", axis)
    end
  
    current_pose = get_actual_tcp_pose()
    insertion_offset = p[0,0,0,0,0,0]
    rq_actual_to_destination = pose_trans(pose_inv(current_pose), rq_ins_destination)
    insertion_offset[axis_index] = rq_actual_to_destination[axis_index]
    insertion_pose = pose_trans(current_pose, insertion_offset)
    distance = point_dist(current_pose, insertion_pose)
    number_of_steps = floor( distance / (speed * rq_controller_time_step) ) + 1
    alpha_step  = 1.0 / number_of_steps
  
    # initialize forcenode
    node_execution_thread = initialise_force_node(position_controlled_direction = axis_index,
                                                  feature = feature_tool,
                                                  max_position_deviation = max_position_deviation)
  
    alpha = 0.0
    surface_found = False
    while (alpha <= 1.0) and (not surface_found):
      alpha = alpha + alpha_step
      interpolated_pose = interpolate_pose(current_pose, insertion_pose, alpha)
      q0 = get_inverse_kin(interpolated_pose) # define waypoint target
      update_servoj_node_target(q0)
      force = 0
      if feature == feature_base:
        force = get_applied_base_force(axis_index)
      elif feature == feature_tool:
        force = get_applied_tcp_force(axis_index)
      end
      if (direction_sign * force) >= compliant_insert_force_threshold:
        surface_found = True
      end
    end
  
    final_pos_reached = (alpha >= 1)
  
    kill_thread( node_execution_thread )
  
    return final_pos_reached
  end # insertion_compliant_move_urcap
  
  def insert_spiral_find_hole(axis = "Z", direction_sign = 1,
                              stop_force_threshold = 3,
                              max_radius = 0.005,
                              radius_incr_per_turn = 0.0003,
                              peck_mode = False,
                              tangential_speed = 0.005):
  
    if (stop_force_threshold < 0) or (stop_force_threshold > 40):
      popup("stop_force_threshold parameter in Newton must be between 0 and 40 Newtons","ERROR rq_insert_spiral_urcap")
      halt
    end
    if (max_radius < 0) or (max_radius > 0.05):
      popup("max_radius parameter must be between 0 mm and 50 mm","ERROR rq_insert_spiral_urcap")
      halt
    end
    if (radius_incr_per_turn < 0.00001) or (radius_incr_per_turn > 0.005):
      popup("radius_incr_per_turn parameter in mm must be between 0.01 mm and 5 mm","ERROR rq_insert_spiral_urcap")
      halt
    end
  
    rq_spiral_not_completed = False
  
    ins_x = 0
    ins_y = 0
    ins_z = 0
    ins_pose = p[0, 0, 0, 0, 0, 0]
    ins_current_pos = p[0, 0, 0, 0, 0, 0]
    ins_actual_angle = 0
    ins_search_result = False
    ins_radius_offset = 0
    ins_PI = 3.14159
    radius_inc_per_rad = radius_incr_per_turn / (2*ins_PI)
    ins_actual_radius = 0.0001  #Start radius
    ins_desired_arc_length = tangential_speed * rq_controller_time_step
  
    sleep(rq_controller_time_step)
    #Find the bore of the part
    ins_current_pos = get_actual_tcp_pose()
    sleep(rq_controller_time_step)
  
    # if axis == "Z"
    search_axis = 2
    other_axis_A = 0
    other_axis_B = 1
    if (axis == "X"):
      search_axis = 0
      other_axis_A = 1
      other_axis_B = 2
    elif (axis == "Y"):
      search_axis = 1
      other_axis_A = 2
      other_axis_B = 0
    end
  
    #********************************************************************************************************************
    #Spiral Search using any Axis
    #********************************************************************************************************************
    while ((ins_actual_radius <= max_radius) and (ins_actual_force_urcap(axis) >= stop_force_threshold)):
      if peck_mode:
        #Fragile mode, the robot rises between each new point
        #Retreat from position
        ins_pose[search_axis] = -0.002 * direction_sign
        next_tcp_pose = pose_trans(ins_current_pos,ins_pose)
        movej(next_tcp_pose)
        sleep(0.1)
        #Rotate
        ins_desired_arc_length = 0.0005
        delta_angle = ins_desired_arc_length / ins_actual_radius #small angle approximation
        ins_actual_angle = ins_actual_angle + delta_angle
  
        ins_pose[other_axis_A] = cos( ins_actual_angle ) * ins_actual_radius
        ins_pose[other_axis_B] = sin( ins_actual_angle ) * ins_actual_radius
  
        ins_actual_radius = ins_actual_angle * radius_inc_per_rad + ins_radius_offset
        next_tcp_pose = pose_trans(ins_current_pos, ins_pose)
        movej(next_tcp_pose)
        sleep(0.1)
        #Re-establish contact with the part
        ins_pose[search_axis] = 0.0005 * direction_sign
        next_tcp_pose = pose_trans(ins_current_pos, ins_pose)
        movel(next_tcp_pose, a=0.6, v=rq_ins_speed_setting)
        sleep(0.2)
      else:
        #standard mode: the Spiral_Search function will maintain contact between both mating parts at all times
        ins_pose[other_axis_A] = cos( ins_actual_angle ) * ins_actual_radius
        ins_pose[other_axis_B] = sin( ins_actual_angle ) * ins_actual_radius
  
        delta_angle = ins_desired_arc_length / ins_actual_radius
        ins_actual_angle = ins_actual_angle + delta_angle
        ins_actual_radius = ins_actual_angle * radius_inc_per_rad + ins_radius_offset
        next_tcp_pose = pose_trans(ins_current_pos,ins_pose)
        next_joint_pos = get_inverse_kin(next_tcp_pose)
        servoj(next_joint_pos, 0.1, 0.1, rq_controller_time_step, 0.05, 500)
      end
    end # while loop
    if (ins_actual_radius <= max_radius ):
      ins_search_result = True
    else:
      ins_search_result = False
      rq_spiral_not_completed = True
    end
    stopj(2)
    return ins_search_result
  
  end # insert_spiral_find_hole
  
  ####################  SPIRAL #############################
  def rq_insert_spiral_urcap(direction = "Z",
                             stop_force_threshold = 3,
                             max_radius = 0.005,
                             radius_incr = 0.0003,
                             peck_mode = False,
                             tangential_speed = 0.005,
                             compliant_insert_force_threshold = 10,
                             spiral_initial_pose_offset_name = "defaultname",
                             intelligent_approach_enabled = False):
  
    max_radius = max_radius / 1000 #TODO: change unit to meters and remove this line
    radius_incr = radius_incr / 1000 #TODO: change unit to meters and remove this line
  
    if (rq_insertion_force_node_id == -1):
      create_all_insertion_nodes()
    end
  
    hole_found = False
    spiral_bottom_target_reached = False
    number_of_failed_spiral_tries = 0
    number_of_spiral_tries_max = 5
    max_position_deviation = max_radius
  
    # define the direction sign from rq_ins_destination
    current_pose = get_actual_tcp_pose()
    rq_actual_to_destination = pose_trans(pose_inv(current_pose), rq_ins_destination)
    axis = str_at(direction, 0)
    direction_sign = 1
    direction = str_cat(axis,"+")
    if axis == "X":
      axis_index = 0
    elif axis == "Y":
      axis_index = 1
    elif axis == "Z":
      axis_index = 2
    else:
      textmsg("spiral insert, invalid direction ", direction)
    end
    if (rq_actual_to_destination[axis_index] < 0):
      direction_sign = -1
      direction = str_cat(axis,"-")
    end
  
    # linearsearch param
    lin_search_stop_force_threshold = compliant_insert_force_threshold
    spiral_initial_pose = get_actual_tcp_pose()
    if intelligent_approach_enabled:
      #adjust position using previous succesfull insertion final position
      spiral_initial_pose_offset = storevar.getvariablepose(spiral_initial_pose_offset_name, p[0,0,0,0,0,0])
      spiral_initial_pose_refined = pose_trans(spiral_initial_pose, spiral_initial_pose_offset)
      movel(spiral_initial_pose_refined, a = 0.1, v = 0.01)
      sleep(0.01)
    end
    while ( (spiral_bottom_target_reached == False) and (number_of_failed_spiral_tries < number_of_spiral_tries_max) ):
      rq_actual_to_destination = pose_trans(pose_inv(get_actual_tcp_pose()), rq_ins_destination)
      max_distance = norm( rq_actual_to_destination[axis_index] )
      contact_initiated = rq_linear_search_urcap(direction, lin_search_stop_force_threshold, tangential_speed, max_distance, 1)
      if contact_initiated:
        new_max_radius = determine_max_spiral_radius_from_actual_position(direction, spiral_initial_pose, max_radius)
        hole_found = insert_spiral_find_hole(axis, direction_sign, stop_force_threshold, new_max_radius, radius_incr, peck_mode, tangential_speed)
        if (hole_found == True): # if hole is found, try to insert
          max_force_control_position_deviation = determine_max_spiral_radius_from_actual_position(direction, spiral_initial_pose, max_radius)
          spiral_bottom_target_reached = insertion_compliant_move_urcap(axis, direction_sign, compliant_insert_force_threshold, tangential_speed, 1, max_force_control_position_deviation)
          if spiral_bottom_target_reached:
            if intelligent_approach_enabled:
              update_spiral_offset(direction, spiral_initial_pose, spiral_initial_pose_offset, spiral_initial_pose_offset_name) # update actual hole position.
            end
          else:
            textmsg("Insertion spiral: could not reach hole bottom")
          end
        else:
          textmsg("Insertion error: hole was not found after contact")
          break
        end
      else: # linear_search reached the teach position without contact
          spiral_bottom_target_reached = True
      end # if contact_initiated
      number_of_failed_spiral_tries = number_of_failed_spiral_tries + 1
    end # while
    return (not spiral_bottom_target_reached)
  end # rq_insert_spiral_urcap
  
  def insertion_finish_move_urcap(direction = "Z+"):
    insertion_offset = p[0,0,0,0,0,0]
    current_pose = get_actual_tcp_pose()
    rq_actual_to_destination = pose_trans(pose_inv(current_pose), rq_ins_destination)
    axis = str_at(direction, 0)
    if axis == "X":
      insertion_offset = p[rq_actual_to_destination[0],0,0,0,0,0]
    elif axis == "Y":
      insertion_offset = p[0,rq_actual_to_destination[1],0,0,0,0]
    elif axis == "Z":
      insertion_offset = p[0,0,rq_actual_to_destination[2],0,0,0]
    else:
      textmsg("insertion_finish_move_urcap, invalid direction ", direction)
    end
    insertion_pose = pose_trans(current_pose, insertion_offset)
    movel(insertion_pose, a=0.05, v=rq_ins_speed_setting)
  end
  
  def rq_xor(a, b):
    return (a and not(b)) or (not(a) and b)
  end
  
  def rq_adapt_force_control_to_direction(position_controlled_direction = 2, feature = 1, max_position_deviation = 0.1):
    force_control_enabled_vector = [True, True, True, False, False, False]
    force_control_enabled_vector[position_controlled_direction] = False
    targetForce = [0, 0, 0, 0, 0, 0]
    max_negative_deviation_vector = [-max_position_deviation, -max_position_deviation, -max_position_deviation, 0, 0, 0]
    max_positive_deviation_vector = [max_position_deviation, max_position_deviation, max_position_deviation, 0, 0, 0]
    max_negative_deviation_vector[position_controlled_direction] = 0
    max_positive_deviation_vector[position_controlled_direction] = 0
    adaptiveStiffness = True
    setup_force_node_on_server(rq_insertion_force_node_id,
                               feature, targetForce,
                               force_control_enabled_vector,
                               max_negative_deviation_vector,
                               max_positive_deviation_vector,
                               adaptiveStiffness)
  end
  
  def initialise_force_node(position_controlled_direction = 2, feature = 1, max_position_deviation = 0.1):
    movej(get_actual_joint_positions()) # This moveJ is used to prevent "another thread is already controlling the robot error".
    rq_adapt_force_control_to_direction(position_controlled_direction = position_controlled_direction,
                                        feature = 1,
                                        max_position_deviation = max_position_deviation)
    set_servoj_node_cmd(get_actual_joint_positions())
    reset_node_executor()
    active_and_reset_node(rq_insertion_force_node_id)
    active_and_reset_node(rq_insertion_servoj_node_id)
    node_execution_thread = run execute_node_thread()
    return node_execution_thread
  end
  
  ####################  ROTATIONAL #############################
  def rq_insert_rotation_urcap(positive_rotation_desired = True,
                               direction="Z",
                               speed = 0.004,
                               force_threshold = 10,
                               rotation_speed = 5,
                               max_angle_deg = 360,
                               peck_mode = False,
                               max_rotation_torque=1):
  
    speed = speed / 1000 # TODO: change speed input units to meters instead of mm and remove this line
    max_force_control_position_deviation = 0.002 # TODO: add a parameter for this in the interface
    max_torque_reached_counter_fail_threshold = 1/rq_controller_time_step # try for about one second
  
    if (rq_insertion_force_node_id == -1):
        create_all_insertion_nodes()
    end
  
    # define the direction sign
    rq_actual_to_destination = pose_trans(pose_inv(get_actual_tcp_pose()), rq_ins_destination)
    axis = str_at(direction, 0)
    direction_sign = 1
    direction = str_cat(axis,"+")
    if axis == "X":
      rq_ins_offset = p[rq_actual_to_destination[0], 0, 0, 0, 0, 0]
      rot_axe = 3
      axis_index = 0
    elif axis == "Y":
      rq_ins_offset = p[0, rq_actual_to_destination[1], 0, 0, 0, 0]
      rot_axe = 4
      axis_index = 1
    elif axis == "Z":
      rq_ins_offset = p[0, 0, rq_actual_to_destination[2], 0, 0, 0]
      rot_axe = 5
      axis_index = 2
    else:
      textmsg("insertion: invalid direction ", direction)
    end
    if (rq_actual_to_destination[axis_index] < 0):
      direction_sign = -1
      direction = str_cat(axis,"-")
      positive_rotation_desired = not positive_rotation_desired
    end
  
    distance_to_destination = norm( rq_actual_to_destination[axis_index] )
  
    contact_with_piece_initiated = rq_linear_search_urcap(direction, force_threshold, speed, distance_to_destination, feature = 1)
  
    if( contact_with_piece_initiated ):
  
      # verify validity of user inputs
      if ((rotation_speed <= 0) or (rotation_speed > 60)):
        popup("rotation speed parameter in degrees / second must be between 0.01 and 60","ERROR rq_insert_rotation_urcap")
        halt
      elif ((max_rotation_torque < 0.01) or (max_rotation_torque > 15)):
        popup("max_rotation_torque parameter in Newton-meter must be between 0.01 and 15","ERROR rq_insert_rotation_urcap")
        halt
      elif ((max_angle_deg <= 1) or (max_angle_deg > 360)):
        popup("max angle parameter in degree must be between 1 and 360","ERROR rq_insert_rotation_urcap")
        halt
      end
  
      # initialize forcenode: adapt to direction
      node_execution_thread = initialise_force_node(position_controlled_direction = axis_index,
                                                    feature = 1,
                                                    max_position_deviation = max_force_control_position_deviation)
  
      if positive_rotation_desired:
        rot_direction_sign = 1
      else:
        rot_direction_sign = -1
      end
      rq_ins_speed_setting = speed
      posrot = p[0,0,0,0,0,0]
      max_rot_angle = d2r(max_angle_deg)
      time_step_signed = rq_controller_time_step * rot_direction_sign * direction_sign
      rot_step = d2r(rotation_speed) * time_step_signed
      rot_step_5deg_per_second = d2r(5) * time_step_signed
  
      line_step = rq_ins_speed_setting * rq_controller_time_step * direction_sign
      rot_actual_angle = 0
      rot_actual_mode = 1 #1= linear, 2 = rotation
      rot_actual_distance = 0
      ins_rotation_initial_pose = get_actual_tcp_pose()
      rq_actual_to_destination = pose_trans( pose_inv(ins_rotation_initial_pose), rq_ins_destination )
      distance_to_destination = norm( rq_actual_to_destination[axis_index] )
      global rq_insertion_max_torque_reached_counter = 0
  
      if peck_mode:
        #peck mode
        positive_rotation_computed = positive_rotation_desired
        while ( (norm(rot_actual_distance) < distance_to_destination) and
                (norm(rot_actual_angle) <= max_rot_angle) and
                (rq_insertion_max_torque_reached_counter < max_torque_reached_counter_fail_threshold) ):
          is_max_torque_reached = norm(get_applied_tcp_force(rot_axe)) > max_rotation_torque
          if (ins_actual_force_urcap(direction) >= force_threshold):
            #goes up
            posrot[axis_index] = rot_actual_distance - 0.002 * direction_sign
            next_tcp_pose = pose_trans(ins_rotation_initial_pose, posrot)
            next_joint_pos = get_inverse_kin(next_tcp_pose)
            node_rpc_server.movejdefinewaypoint(rq_insertion_movej_node_id, next_joint_pos, 0.4, 0.4)
            execute_node(rq_insertion_movej_node_id, False )
            #rotate
            rot_actual_angle = compute_rotation_next_angle(rot_actual_angle, 285 * rot_step, is_max_torque_reached) # value of 285 define the peck mode "step size". determined ad oc
            posrot[rot_axe] = rot_actual_angle
            next_tcp_pose = pose_trans(ins_rotation_initial_pose, posrot)
            next_joint_pos = get_inverse_kin(next_tcp_pose)
            node_rpc_server.movejdefinewaypoint(rq_insertion_movej_node_id, next_joint_pos, 1, 1)
            execute_node(rq_insertion_movej_node_id, False )
            #go back in touch with the part
            posrot[axis_index] = rot_actual_distance
            next_tcp_pose = pose_trans(ins_rotation_initial_pose, posrot)
            next_joint_pos = get_inverse_kin(next_tcp_pose)
            node_rpc_server.movejdefinewaypoint(rq_insertion_movej_node_id, next_joint_pos, 0.4, 0.3)
            execute_node(rq_insertion_movej_node_id, False )
            sleep(0.1)
          else:
            rq_insertion_max_torque_reached_counter = 0
            rot_actual_distance = rot_actual_distance + line_step
            posrot[axis_index] = rot_actual_distance
            next_tcp_pose = pose_trans(ins_rotation_initial_pose, posrot)
            next_joint_pos = get_inverse_kin(next_tcp_pose)
            update_servoj_node_target(next_joint_pos)
            if (rq_active_node != rq_insertion_servoj_node_id):
              active_and_reset_node(rq_insertion_servoj_node_id)
            end
          end # if
        end # while
      else:
        #normal mode
        while ( (norm(rot_actual_distance) <= distance_to_destination) and
                (norm(rot_actual_angle) <= max_rot_angle) and
                (rq_insertion_max_torque_reached_counter < max_torque_reached_counter_fail_threshold) ):
          is_max_torque_reached = norm(get_applied_tcp_force(rot_axe)) > max_rotation_torque
          if ( norm(get_applied_tcp_force(axis_index)) >= force_threshold ):
            if (rot_actual_mode == 1):
              rot_actual_distance = rot_actual_distance - line_step
              posrot[axis_index] = rot_actual_distance
            end
            limited_rotation_step = limit_rotation_step_when_close_to_max_angle(rot_step, rot_step_5deg_per_second, max_rot_angle, rot_actual_angle)
            rot_actual_angle = compute_rotation_next_angle(rot_actual_angle, limited_rotation_step, is_max_torque_reached)
            posrot[rot_axe] = rot_actual_angle
            rot_actual_mode = 2
          else:
            rq_insertion_max_torque_reached_counter = 0
            rot_actual_distance = rot_actual_distance + line_step
            posrot[axis_index] = rot_actual_distance
            rot_actual_mode = 1
          end # if
          next_tcp_pose = pose_trans(ins_rotation_initial_pose, posrot)
          next_joint_pos = get_inverse_kin(next_tcp_pose)
          update_servoj_node_target(next_joint_pos)
        end # while
      end # if peck_mode
  
      kill_thread( node_execution_thread )
      stopj(2)
      rq_rotation_not_completed = ( (norm(rot_actual_angle) > max_rot_angle) or
                                    (rq_insertion_max_torque_reached_counter >= max_torque_reached_counter_fail_threshold) )
    else: # initial find_surface was unsuccessfull, assume a direct hit to target, which is a success
      rq_rotation_not_completed = False
    end # if contact_with_piece_initiated
  
    return rq_rotation_not_completed
  end # insert rotation 2
  
  def limit_rotation_step_when_close_to_max_angle(rot_step, minimal_rot_step, max_rot_angle, rot_actual_angle):
    rot_deceleration_angle_distance = d2r(3)
    rot_direction = 1
    if( rot_step < 0 ):
      rot_direction = -1
      rot_step = -1 * rot_step # get positive rot_step for calculation. Direction sign is re-introduced at the end.
    end
    angle_distance_to_max_rot_angle = max_rot_angle - norm(rot_actual_angle)
    if( (angle_distance_to_max_rot_angle < rot_deceleration_angle_distance) and (rot_step > minimal_rot_step) ):
      decelaration_slope = (rot_step - minimal_rot_step) / rot_deceleration_angle_distance
      rot_step_limited = decelaration_slope * angle_distance_to_max_rot_angle + minimal_rot_step
    else:
      rot_step_limited = rot_step
    end
    return ( rot_direction * rot_step_limited )
  end
  
  def compute_rotation_next_angle(current_angle, step, is_max_torque_reached):
  #This function compute the rotation angle for rotational insertion by
  # incrementing the current angle by the desired step size.
  # If the maximal torque is reached, the rotation goes backward to
  # return to a admissible torque. In the backward direction,
  # a smaller step size is used to prevent constant oscillation between to steps
    if (is_max_torque_reached):
        rq_insertion_max_torque_reached_counter = rq_insertion_max_torque_reached_counter + 1
        new_angle = current_angle - 0.8 * step
    else:
        new_angle = current_angle + step
    end
    return new_angle
  end
  
  def center_one_axis(axis, lin_search_stop_force_threshold, speed, max_distance, feature):
    # Initiate contact in forward direction
    contact_initiated = rq_linear_search_urcap( str_cat(axis, "+"), lin_search_stop_force_threshold, speed, max_distance, feature)
    if contact_initiated:
      forward_contact_pose = get_actual_tcp_pose()
      # Initiate contact in reverse direction
      contact_initiated = rq_linear_search_urcap(str_cat(axis, "-"), lin_search_stop_force_threshold, speed, max_distance, feature)
      if contact_initiated:
        reverse_contact_pose = get_actual_tcp_pose()
        # Go to average of contact points
        pose_center_1 = interpolate_pose(forward_contact_pose, reverse_contact_pose, 0.5)
        movel(pose_center_1, a=0.6, v=speed)
      end
    end
    return contact_initiated
  end
  
  def rq_insert_recenter_urcap(axis = "Z", max_distance = 0.1, speed = 0.005, feature = 1, lin_search_stop_force_threshold = 5):
  
    if (max_distance < 0) or (max_distance > 1):
      popup("max_distance parameter in m must be between 0 and 1","ERROR rq_insert_recenter_urcap")
      halt
    elif (speed < 0.0001) or (speed > 0.5):
      popup("max_radius parameter in mm must be between 0.0001m/s and 0.5m/s","ERROR rq_insert_recenter_urcap")
      halt
    end
  
    #--------------------------------------------------------------------------------------------------------------------
    #For insertion in the X axis
    #--------------------------------------------------------------------------------------------------------------------
    if (axis == "X"):
      recenter_axis_1 = "Y"
      recenter_axis_2 = "Z"
    #--------------------------------------------------------------------------------------------------------------------
    #For insertion in the Y axis
    #--------------------------------------------------------------------------------------------------------------------
    elif (axis == "Y"):
      recenter_axis_1 = "X"
      recenter_axis_2 = "Z"
    #--------------------------------------------------------------------------------------------------------------------
    #For insertion in the Z axis
    #--------------------------------------------------------------------------------------------------------------------
    elif (axis == "Z"):
      recenter_axis_1 = "X"
      recenter_axis_2 = "Y"
    end
  
    recenter_successfull = center_one_axis(recenter_axis_1, lin_search_stop_force_threshold, speed, max_distance, feature)
    if recenter_successfull:
      recenter_successfull = center_one_axis(recenter_axis_2, lin_search_stop_force_threshold, speed, max_distance, feature)
    end
  
    if (recenter_successfull == False):
      textmsg("rq_insert_recenter_urcap failed, could not initiate contact with piece")
    end
  
    return recenter_successfull
  end # rq_insert_recenter_urcap
  
  # ******************* MAIN of Insertion Preamble *******************
  storevar.clearall()
  global rq_insertion_force_node_id = -1
  #************************************************
  #Function:  rq_linear_search_urcap(direction="Z+", force[N] = 10, speed[m/s] = 0.004, max_distance[m] = 0.02)
  #   Find a specific force in the direction of "direction".
  #   Robot will move towards a max_distance from the current position in the tool frame
  #   Return True if the force is detected during the robot motion
  #
  #************************************************
  def rq_linear_search_urcap(direction="Z+", force_threshold = 10, speed = 0.004, max_distance = 0.02, feature = 0 ):
  
    if (max_distance > 2.0):
      popup("maximum distance parameter in meters must be between 0 and 2.0","ERROR rq_linear_search_urcap")
      halt
    elif (speed < 0.0001) or (speed > 0.15):
      popup("speed parameter in mm/s must be between 0.1 and 150","ERROR rq_linear_search_urcap")
      halt
    elif (force_threshold < 0.0) or (force_threshold > 200):
      popup("Force parameter in Newtons must be between 0 and 200","ERROR rq_linear_search_urcap")
      halt
    elif (feature != 0) and (feature != 1):
      popup("feature value should be 0 for base or 1 for tool","ERROR rq_linear_search_urcap")
      halt
    end
  
    feature_base = 0
    feature_tool = 1
    steptime = rq_controller_time_step
    force_index = 0
  
    axis = str_at(direction, 0)
    sign = str_at(direction, 1)
  
    direction_sign = 1
    if sign == "-":
      direction_sign = -1
      max_distance = max_distance * direction_sign
    end
  
    pose_offset = p[0,0,0,0,0,0]
    if (axis == "X") or (axis == "x"):
      pose_offset = p[max_distance,0,0,0,0,0]
      force_index = 0
    elif (axis == "Y") or (axis == "y"):
      pose_offset = p[0,max_distance,0,0,0,0]
      force_index = 1
    elif (axis == "Z") or (axis == "z"):
      pose_offset = p[0,0,max_distance,0,0,0]
      force_index = 2
    else:
      popup("direction parameter must be X+, X-, Y+, Y-, Z+ or Z-","ERROR rq_linear_search_urcap")
      halt
    end
  
    pose_from = get_actual_tcp_pose()
    pose_to = pose_from
    if feature == feature_base:
      pose_to = pose_add(pose_from, pose_offset)
    elif feature == feature_tool:
      pose_to = pose_trans(pose_from, pose_offset)
    end
  
    distance = point_dist(pose_from, pose_to)
    number_pose_interpolate = floor(distance / (speed * steptime)) + 1
    delta_alpha = 1.0 / number_pose_interpolate
  
    alpha = 0.0
    local surface_found = False
  
    pose_step = 0
    end_pose_pause_time = 0.2 # to refine
    max_pose_steps = number_pose_interpolate + end_pose_pause_time/steptime
    while (pose_step < max_pose_steps) and (not surface_found):
      pose_step = pose_step + 1
      alpha = pose_step * delta_alpha
      if (alpha < 1.0):
        pose_interpolate = interpolate_pose(pose_from, pose_to, alpha)
      else:
        pose_interpolate = pose_to
      end
  
      servoj(get_inverse_kin(pose_interpolate), 0.1, 0.1, steptime, 0.05, 500)
  
      force = 0
      if feature == feature_base:
        force = get_applied_base_force(force_index)
      elif feature == feature_tool:
        force = get_applied_tcp_force(force_index)
      end
  
      if (direction_sign * force) >= force_threshold:
        surface_found = True
      end
    end
  
    return surface_found
  
  end
  
    ##############################################
    # OFFSET FEATURE-RELATED VARIABLES AND METHODS
    ##############################################
    def cross_product(vector1,vector2):
      v_temp=[0,0,0]
      v_temp[0]=vector1[1]*vector2[2]-vector1[2]*vector2[1]
      v_temp[1]=vector1[2]*vector2[0]-vector1[0]*vector2[2]
      v_temp[2]=vector1[0]*vector2[1]-vector1[1]*vector2[0]
      return v_temp
    end
  
    def relocate_xyzr(init_feature, init_touch_pose, touch_pose):
      init_touch_pose_2_init_feature = pose_trans( pose_inv(init_touch_pose), init_feature)
      new_feature = pose_trans( touch_pose, init_touch_pose_2_init_feature )
  
      return new_feature
    end
  
    def relocate_orientation(touch1_init_pose, touch2_init_pose, feature_init_pose, touch1_pose, touch2_pose):
      #when relocating using 2 touch, the center of rotation is around touch point 1 (this could be changed)
  
      # initial touch2 pose in initial touch 1 pose frame:
      touch2_initial_pose_in_touch1_initial_pose_frame = pose_trans(pose_inv(touch1_init_pose), touch2_init_pose)
  
      # find theoric touch2_pose if no rotation
      touch2_pose_if_no_rotation = pose_trans(touch1_pose, touch2_initial_pose_in_touch1_initial_pose_frame)
  
      # vectors touch1 to touch2
      touch1_pose_to_touch2_pose = pose_trans(pose_inv(touch1_pose), touch2_pose)
      touch1_pose_to_touch2_pose_if_no_rotation = pose_trans(pose_inv(touch1_pose), touch2_pose_if_no_rotation)
  
      #angle axis calculation
      normal_vector = cross_product(touch1_pose_to_touch2_pose_if_no_rotation, touch1_pose_to_touch2_pose)
      normal_vector_norm = norm(normal_vector)
      if (normal_vector_norm > 10e-6):
        rotation_angle_rad = asin( normal_vector_norm / (norm(touch1_pose_to_touch2_pose_if_no_rotation) * norm(touch1_pose_to_touch2_pose) ) )
        normal_vector_to_angle_axis_multiply_norm_factor = rotation_angle_rad / normal_vector_norm
        angle_axis = [normal_vector[0] * normal_vector_to_angle_axis_multiply_norm_factor, normal_vector[1] * normal_vector_to_angle_axis_multiply_norm_factor, normal_vector[2] * normal_vector_to_angle_axis_multiply_norm_factor]
        rotation_offset_pose = p[0, 0, 0, angle_axis[0], angle_axis[1], angle_axis[2]]
  
        #rotate touch1 pose using touch2 information
        touch1_pose_rotated = pose_trans(touch1_pose, rotation_offset_pose)
      else:
        touch1_pose_rotated = touch1_pose
      end
  
      # relocate the feature using touch1_rotated_pose
      return relocate_xyzr(feature_init_pose, touch1_init_pose, touch1_pose_rotated)
    end
  
    def relocate_1_touch(touch_init_pose, touch_pose, feature_init_pose, feature_actual_pose):
      touch_initial_pose_in_initial_feature_frame = pose_trans(pose_inv(feature_init_pose), touch_init_pose)
      touch_actual_pose_in_actual_feature_frame = pose_trans(pose_inv(feature_actual_pose), touch_pose)
  
      # difference between touch poses in their respective feature frame
      touch_pose_offset = pose_sub(touch_actual_pose_in_actual_feature_frame, touch_initial_pose_in_initial_feature_frame)
  
      # remove all rotation from offset
      touch_pose_offset[3] = 0
      touch_pose_offset[4] = 0
      touch_pose_offset[5] = 0
  
      # apply pose offset to actual feature
      return pose_trans(feature_actual_pose, touch_pose_offset)
    end
    ##############################################
    # PALLETIZER INITIALIZATION
    ##############################################
    if(not palletizerXmlRpcClient.acknowledgePalletStates()):
      checkForScriptPreparationException()
      halt
    end
  
    ##############################################
    # PALLETIZER-RELATED VARIABLES AND METHODS
    ##############################################
    def rq_is_last_box_of_layer(box_id, end_of_layer_boxes, is_depalletizing):
      number_of_layers = length(end_of_layer_boxes)
      if is_depalletizing:
        boxes_on_pallet = end_of_layer_boxes[number_of_layers - 1] - box_id
      else:
        boxes_on_pallet = box_id
      end
      i = 0
      while i < number_of_layers:
        if boxes_on_pallet == end_of_layer_boxes[i]:
          return True
          break
        end
        i = i + 1
      end
      return False
    end
  
    palletizerXmlRpcClient.setCurrentPalletizerNode("")
  
    def rq_get_nb_processed_boxes():
      rq_palletizer_uuid = palletizerXmlRpcClient.getCurrentPalletizerNode()
      if rq_palletizer_uuid == "":
        popup("rq_get_nb_processed_boxes() should only be called from within a Palletizer node.", title="Palletizer", error=True, blocking=True)
        halt
      end
  
      rq_box_count = palletizerXmlRpcClient.getCurrentBoxCount(rq_palletizer_uuid)
      if rq_box_count == -1:
        popup("Invalid Palletizer node id used for rq_get_nb_processed_boxes()", title="Palletizer", error=True, blocking=True)
        halt
      end
      return rq_box_count
    end
  
    def rq_set_pallet_completed():
      rq_palletizer_uuid = palletizerXmlRpcClient.getCurrentPalletizerNode()
      if rq_palletizer_uuid == "":
        popup("rq_set_pallet_completed() should only be called from within a Palletizer node.", title="Palletizer", error=True, blocking=True)
        halt
      end
  
      palletizerXmlRpcClient.skipToAfterPallet(rq_palletizer_uuid)
    end
  
    def rq_demo_mode_switch_palletizer_mode():
      palletizerXmlRpcClient.demoModeFakePalletSwapAndAndSwitchPalletizerMode()
    end
  
    def rq_linear_axis_scan(halt_on_error=True):
      local succeeded = False
      local error_message = ""
  
      if not node_rpc_server.linearaxisconnected():
        succeeded = node_rpc_server.linearaxisscan()
        if succeeded:
          textmsg("Linear axis scanned successfully")
        else:
          error_message = "rq_linear_axis_scan() was unable to find linear axis"
        end
      else:
        succeeded = True
        textmsg("Linear axis already connected")
      end
  
      if not succeeded:
        if halt_on_error:
          popup(error_message, title="Linear Axis", error=True, blocking=True)
          halt
        else:
          textmsg(error_message)
        end
      end
  
      return succeeded
    end
  
    def rq_linear_axis_start(halt_on_error=True):
      local succeeded = False
      local error_message = ""
  
      if not node_rpc_server.linearaxisconnected():
        error_message = "rq_linear_axis_start() was unable to start linear axis : linear axis not connected"
      else:
        succeeded = node_rpc_server.linearaxisstart()
        if succeeded:
          textmsg("Linear axis started successfully")
        else:
          error_message = "rq_linear_axis_start() was unable to start linear axis"
        end
      end
  
      if not succeeded:
        if halt_on_error:
          popup(error_message, title="Linear Axis", error=True, blocking=True)
          halt
        else:
          textmsg(error_message)
        end
      end
  
      return succeeded
    end
  
    def rq_linear_axis_disable(halt_on_error=True):
      local succeeded = False
      local error_message = ""
  
      if not node_rpc_server.linearaxisconnected():
        error_message = "rq_linear_axis_disable() was unable to disable linear axis : linear axis not connected"
      else:
        succeeded = node_rpc_server.linearaxisdisable()
        if succeeded:
          textmsg("Linear axis disabled successfully")
        else:
          error_message = "rq_linear_axis_disable() was unable to disable linear axis"
        end
      end
  
      if not succeeded:
        if halt_on_error:
          popup(error_message, title="Linear Axis", error=True, blocking=True)
          halt
        else:
          textmsg(error_message)
        end
      end
  
      return succeeded
    end
    ###############################################################
    # Linear Axis Move related methods
    ###############################################################
    def verify_is_in_linear_axis_range(target_axis_position):
      axis_position_range = node_rpc_server.linearaxisgetpositionrange()
  
      if target_axis_position < axis_position_range[0] or target_axis_position > axis_position_range[1]:
        textmsg("Linear axis target position : ", target_axis_position)
        textmsg("Linear axis position range : ", axis_position_range)
        popup("Linear axis position is unreachable.", "Linear Axis Move", blocking=True, error=True)
        halt
      end
    end
  
    def rq_get_linear_axis_pos():
        axis_position = node_rpc_server.linearaxisgetactualposition()
        textmsg("Linear axis actual position : ", axis_position)
        return axis_position
    end
    global servojId = 2
  rq_collision_detection_stop()
  # end: URCap Installation Node
  global Waypoint_1_p=p[-.630407124235, -.296528896423, .136221788588, -1.229898520893, -1.220237997586, 1.196581871558]
  global Waypoint_1_q=[0.3692786395549774, -0.48095889509234624, 1.5607193152057093, 1.2628416258045654, -1.8477709929095667, -0.2628729979144495]
  global Waypoint_15_p=p[-.361117650575, -.287403925296, .558950815511, 1.229848458813, -1.214260238333, -1.194290411881]
  global Waypoint_15_q=[0.5462231636047363, -1.299070582990982, 1.9646461645709437, 1.6651934820362548, -1.9007957617389124, -0.3136795202838343]
  global Waypoint_16_p=p[-.635651184181, -.285475736443, .163792338200, -1.226772045383, -1.230615482384, 1.215161969706]
  global Waypoint_16_q=[0.33720043301582336, -0.5425684016994019, 1.5998790899859827, 1.293642206782959, -1.8175771872149866, -0.22054559389223272]
  global Waypoint_18_p=p[-.590750873318, -.139462379422, .307521318077, -1.226623837333, -1.230682192904, 1.215210985314]
  global Waypoint_18_q=[0.017998505383729935, -0.983365074997284, 2.003566090260641, 1.3587981897541503, -1.5887616316424769, 0.0046208566054701805]
  global Waypoint_19_p=p[-.489991526188, -.113644627590, .259460393076, 1.201174517973, 2.902848019224, .000152145723]
  global Waypoint_19_q=[-0.1367095152484339, -1.5985428295531214, 2.013503376637594, 3.7498223024555664, -0.966959301625387, -0.7424333731280726]
  global Waypoint_20_p=p[-.612491367170, -.235853461879, .172873629899, -.140583563832, 3.133080579292, -.008359806023]
  global Waypoint_20_q=[0.06762700862884163, -1.1663139852772701, 1.5767416058064176, 4.3262812889695015, -0.7725755715536655, -1.5973673863789557]
  global Waypoint_17_p=p[-.615869094666, .017644113422, .165499884759, -.140452718959, 3.133036764696, -.008284212182]
  global Waypoint_17_q=[-0.3403123060809534, -1.2111049455455323, 1.5604561010943812, 4.76623152473525, -0.8623440901385706, -2.1475346724139612]
  def calculate_point_to_move_towards(feature, direction, position_distance):
    local posDir=[direction[0], direction[1], direction[2]]
    if (norm(posDir) < 1e-6):
      return get_target_waypoint()
    end
    local direction_vector_normalized=normalize(posDir)
    local displacement_pose=p[direction_vector_normalized[0] * position_distance,direction_vector_normalized[1] * position_distance,direction_vector_normalized[2] * position_distance,0,0,0]
    local wanted_displacement_in_base_frame=pose_sub(pose_trans(feature, displacement_pose), feature)
    return pose_add(get_target_waypoint(), wanted_displacement_in_base_frame)
  end
  global Waypoint_31_p=p[-.620705477863, -.281438793834, .421856325693, .442241084011, -1.957788574586, 1.869446182328]
  global Waypoint_31_q=[-0.12204867998232061, -1.0642738503268738, 1.6338570753680628, 3.5765363413044433, 0.7937431335449219, -1.4932802359210413]
  global Waypoint_26_p=p[-.617598261035, -.285662220360, .447887815636, .257865385762, -2.080912438304, 2.083743282101]
  global Waypoint_26_q=[-0.11151010194887334, -1.1329282981208344, 1.640463654194967, 3.861135168666504, 0.8244242668151855, -1.443099323903219]
  global Waypoint_27_p=p[-.615450775964, -.280884121138, .196979310137, .186167416068, 2.228337584014, -2.171969679542]
  global Waypoint_27_q=[-0.1276615780040693, -0.8622460424642133, 1.8860316040763472, 3.7341520268710178, 0.7572025320077823, -1.4955693866647657]
  global Waypoint_30_p=p[-.495207212260, .028978859858, .374875227740, -1.178012939947, -1.429291973212, -1.137856928903]
  global Waypoint_30_q=[0.11711236089468002, -1.3994892698577424, 1.594299618397848, 0.04228417455639644, 2.3511312007904053, 1.775545358657837]
  global Waypoint_28_p=p[-.619839383396, .056782252985, .465016731825, -1.038625099662, -1.449976544355, -1.422633023255]
  global Waypoint_28_q=[0.05380272992719082, -1.049030689942267, 0.9311039597756929, 0.4607086029667755, 2.3871604587925592, 1.6100670367673615]
  global Waypoint_29_p=p[-.612286560883, .054274106350, .219229730051, -1.559816907949, -.273312861706, -.250072536663]
  global Waypoint_29_q=[0.054913531722276865, -0.9118303640193561, 1.8039951750427967, -2.1737980972152133, 2.382701554301983, 1.5099209384548118]
  global Waypoint_32_p=p[-.579373695775, -.099247829592, .329850635698, -1.080350767069, -1.256308939183, .949442715947]
  global Waypoint_32_q=[-0.0684283415423792, -1.6360942325987757, 2.298481289540426, -1.426223100428917, 1.424859881401062, 2.9433958530426025]
  global Waypoint_14_p=p[-.614394729902, -.211304335396, .158056240121, .891947218350, -1.398909790489, .897150739920]
  global Waypoint_14_q=[0.06688901782035828, -1.2062542003444214, 2.0273497740374964, -0.8648550671390076, 1.2756636142730713, -1.4902976194964808]
  global Waypoint_7_p=p[-.620397442971, -.213913387421, .513045981562, .892039726095, -1.398788049866, .897149319987]
  global Waypoint_7_q=[0.07276958227157593, -1.4890245211175461, 1.3829248587237757, 0.06161419927563472, 1.2746750116348267, -1.4881308714496058]
  global Waypoint_8_p=p[-.623058142139, -.006084652142, .504453333345, -1.537936671521, .945649868765, 1.518782592931]
  global Waypoint_8_q=[-0.19953567186464483, -1.5323755119792004, 1.506406609212057, 0.09952227651562495, 1.710647463798523, 1.639211893081665]
  global Waypoint_9_p=p[-.617185750904, -.003635744661, .159537482557, -1.537967820599, .945518640189, 1.518830856235]
  global Waypoint_9_q=[-0.2093423048602503, -1.1935233038714905, 2.0858619848834437, -0.8191923064044495, 1.7075483798980713, 1.6363801956176758]
  global Waypoint_11_p=p[-.622642705290, .073148999400, .262251367419, 2.006728907347, -1.984988481834, -.422320036043]
  global Waypoint_11_q=[-0.4727992403938508, -1.1931046923095465, 2.20874207186656, 2.5557256410267852, -1.073340525120777, -0.12859028859736554]
  global Waypoint_13_p=p[-.619354417627, -.281828120597, .259920784695, 2.006644977079, -1.985054067831, -.422363830708]
  global Waypoint_13_q=[0.34064259421721754, -1.0461214725192036, 1.9566921865069062, 2.624216301931531, -1.8247852350844171, 6.475282443617515]
  global Waypoint_10_p=p[-.530531214308, -.291051767939, .144441273867, -2.230084186391, -.010541297178, 2.193479360406]
  global Waypoint_10_q=[-0.013276402150289357, -1.1500203174403687, 2.071028534566061, -0.8113540571979065, 0.7900835871696472, 1.5619460344314575]
  global Waypoint_12_p=p[-.538683230436, -.290103741120, .513861909890, -2.230228499578, -.010549727182, 2.193403454803]
  global Waypoint_12_q=[-0.014661137257711232, -1.5093185876360913, 1.4554780165301722, 0.1618388134190063, 0.7814483642578125, 1.5644021034240723]
  global Waypoint_21_p=p[-.538097215403, -.306156956945, .483390788397, 1.229893655187, -1.218513911680, -1.215360660983]
  global Waypoint_21_q=[0.3963368409401085, -1.3775476134256621, 1.8729893210491355, -1.2799846272166313, 1.7980125332058048, 2.916890895394065]
  global Waypoint_22_p=p[-.536010150874, .078845475801, .482449152758, 1.229938842496, -1.218372029627, -1.215426474968]
  global Waypoint_22_q=[-0.5032866636859339, -1.6272269688048304, 2.161717716847555, -1.3892281365445633, 1.1609302759170532, 3.565915822982788]
  global Waypoint_23_p=p[-.536856714168, .057735272175, .516337801355, .007484190804, -1.587582998653, -.015116946919]
  global Waypoint_23_q=[-0.06483646191397252, -1.5618650824148386, 1.4615836328585363, 0.02914312769531069, 2.287159484941591, 4.71271091019117]
  global Waypoint_24_p=p[-.528032248544, .056709628722, .114658997919, .007476027220, -1.587403647508, -.015130351722]
  global Waypoint_24_q=[-0.06486922899355108, -1.1597505372813721, 2.1470850149737757, -1.0617385071567078, 2.2945711612701416, 4.708008766174316]
  global Waypoint_38_p=p[-.528301525964, .092928967835, .137544225611, 1.229518931609, -1.218164277810, -1.215725675197]
  global Waypoint_38_q=[-0.5465338865863245, -0.6870334309390564, 2.310338083897726, -2.490049978295797, 1.1306086778640747, 3.593946933746338]
  global Waypoint_25_p=p[-.530503307682, -.310799634742, .138539696150, 1.229529893186, -1.218212145518, -1.215748001331]
  global Waypoint_25_q=[0.4098140597343445, -0.6766109031489869, 2.0097950140582483, -2.1218296490111292, 1.8071534633636475, 2.900541067123413]
  global Waypoint_2_p=p[-.645397834819, -.296455318143, .135893598346, -1.229860133264, -1.220302156683, 1.196482482900]
  global Waypoint_2_q=[0.3583512306213379, -0.46596868455920415, 1.5182254950152796, 1.2925869661518554, -1.840168301259176, -0.25457460085024053]
  global Waypoint_3_p=p[-.653334935266, -.295509469566, .495795086421, -1.229748130315, -1.220382999730, 1.196524228234]
  global Waypoint_3_q=[0.3499549627304077, -1.030382589702942, 1.4344146887408655, 1.9436744886585693, -1.8333328405963343, -0.2433412710772913]
  global Waypoint_4_p=p[-.651378944197, .064515214832, .494965709811, -1.229676952695, -1.220192791007, 1.196530019033]
  global Waypoint_4_q=[-0.45318347612489873, -1.2302940350821991, 1.7351792494403284, 1.8209370809742431, -1.2614148298846644, 0.326932430267334]
  global Waypoint_5_p=p[-.643443913507, .063548429699, .135045355381, -1.229578554448, -1.220152089579, 1.196541404830]
  global Waypoint_5_q=[-0.45803863206972295, -0.5575369161418458, 1.8256614843951624, 1.0582493978687744, -1.2579148451434534, 0.32477086782455444]
  global Waypoint_6_p=p[-.645385399314, -.296430462109, .135967790852, -1.229561513341, -1.220089907423, 1.196571909520]
  global Waypoint_6_q=[0.3582976460456848, -0.4660030168345948, 1.5182111899005335, 1.2923266130634765, -1.8399995009051722, -0.25468570390810186]
  def sandRebate():
    $ 28 "sandRebate" "noBreak"
    $ 29 "MoveJ"
    $ 30 "Waypoint_16" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_16_p)), qnear=Waypoint_16_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 31 "Waypoint_18" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_18_p)), qnear=Waypoint_18_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 32 "Waypoint_19" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_19_p)), qnear=Waypoint_19_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 33 "Waypoint_20" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_20_p)), qnear=Waypoint_20_q), a=1.3962634015954636, v=1.0471975511965976)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Find Surface
    $ 34 "Find Surface"
    zero_ftsensor()
    sleep(0.1)
    surface_found = rq_linear_search_urcap("Z+", 10.000, 0.005000, 0.100000, 1)
    storevar.setvariablepose("rq_findSurface_48dfa941-1460-4d19-a00f-d8f437f52397_exitPosition", get_actual_tcp_pose())
    $ 35 "'Add Stop conditions from the Find Surface node'" "noBreak"
    # 'Add Stop conditions from the Find Surface node'
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 36 "Start tool"
    set_standard_digital_out(3, True)
    # end: URCap Program Node
    $ 37 "Force"
    sleep(0.02)
    zero_ftsensor()
    force_mode(tool_pose(), [0, 0, 1, 0, 0, 0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0], 2, [0.1, 0.1, 0.15, 0.3490658503988659, 0.3490658503988659, 0.3490658503988659])
    $ 38 "MoveL" "noBreak"
    $ 39 "Waypoint_17" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_17_p)), a=1.2, v=0.06)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 40 "Stop tool" "noBreak"
    set_standard_digital_out(3, False)
    # end: URCap Program Node
    end_force_mode()
    stopl(5.0)
    $ 41 "MoveL"
    $ 42 "Direction: Tool Z-"
    global move_thread_flag_42=0
    thread move_thread_42():
      enter_critical
      move_thread_flag_42 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_42 = 2
      exit_critical
    end
    move_thread_flag_42 = 0
    move_thread_han_42 = run move_thread_42()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_42 > 1):
        join move_thread_han_42
        $ 43 "Until (distance)"
        break
      end
      sync()
    end
    $ 44 "Direction: CubeFront Z+"
    global move_thread_flag_44=0
    thread move_thread_44():
      enter_critical
      move_thread_flag_44 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.15)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_44 = 2
      exit_critical
    end
    move_thread_flag_44 = 0
    move_thread_han_44 = run move_thread_44()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_44 > 1):
        join move_thread_han_44
        $ 45 "Until (distance)"
        break
      end
      sync()
    end
    $ 46 "MoveJ"
    $ 47 "Waypoint_31" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_31_p)), qnear=Waypoint_31_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 48 "Waypoint_26" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.300286591152, -.149331691834, .650647942655, -1.193662016482, -1.190171861546, -1.213677846742], Waypoint_26_p)), qnear=Waypoint_26_q), a=1.3962634015954636, v=1.0471975511965976)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Find Surface
    $ 49 "Find Surface"
    zero_ftsensor()
    sleep(0.1)
    surface_found = rq_linear_search_urcap("Z+", 10.000, 0.005000, 0.100000, 1)
    storevar.setvariablepose("rq_findSurface_3ee7133c-89f8-43b4-bdcd-a21fe419666d_exitPosition", get_actual_tcp_pose())
    $ 50 "'Add Stop conditions from the Find Surface node'" "noBreak"
    # 'Add Stop conditions from the Find Surface node'
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 51 "Start tool"
    set_standard_digital_out(3, True)
    # end: URCap Program Node
    $ 52 "Force"
    sleep(0.02)
    zero_ftsensor()
    force_mode(tool_pose(), [0, 0, 1, 0, 0, 0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0], 2, [0.1, 0.1, 0.15, 0.3490658503988659, 0.3490658503988659, 0.3490658503988659])
    $ 53 "MoveL" "noBreak"
    $ 54 "Waypoint_27" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_27_p)), a=1.2, v=0.06)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 55 "Stop tool" "noBreak"
    set_standard_digital_out(3, False)
    # end: URCap Program Node
    end_force_mode()
    stopl(5.0)
    $ 56 "MoveL"
    $ 57 "Direction: Tool Z-"
    global move_thread_flag_57=0
    thread move_thread_57():
      enter_critical
      move_thread_flag_57 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_57 = 2
      exit_critical
    end
    move_thread_flag_57 = 0
    move_thread_han_57 = run move_thread_57()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_57 > 1):
        join move_thread_han_57
        $ 58 "Until (distance)"
        break
      end
      sync()
    end
    $ 59 "Direction: CubeFront Z+"
    global move_thread_flag_59=0
    thread move_thread_59():
      enter_critical
      move_thread_flag_59 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.15)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_59 = 2
      exit_critical
    end
    move_thread_flag_59 = 0
    move_thread_han_59 = run move_thread_59()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_59 > 1):
        join move_thread_han_59
        $ 60 "Until (distance)"
        break
      end
      sync()
    end
    $ 61 "MoveJ"
    $ 62 "Waypoint_30" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_30_p)), qnear=Waypoint_30_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 63 "Waypoint_28" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_28_p)), qnear=Waypoint_28_q), a=1.3962634015954636, v=1.0471975511965976)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Find Surface
    $ 64 "Find Surface"
    zero_ftsensor()
    sleep(0.1)
    surface_found = rq_linear_search_urcap("Z+", 10.000, 0.005000, 0.100000, 1)
    storevar.setvariablepose("rq_findSurface_0f0dcade-d478-4fc4-9bf8-a680beb3084f_exitPosition", get_actual_tcp_pose())
    $ 65 "'Add Stop conditions from the Find Surface node'" "noBreak"
    # 'Add Stop conditions from the Find Surface node'
    # end: URCap Program Node
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 66 "Start tool"
    set_standard_digital_out(3, True)
    # end: URCap Program Node
    $ 67 "Force"
    sleep(0.02)
    zero_ftsensor()
    force_mode(tool_pose(), [0, 0, 1, 0, 0, 0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0], 2, [0.1, 0.1, 0.15, 0.3490658503988659, 0.3490658503988659, 0.3490658503988659])
    $ 68 "MoveL" "noBreak"
    $ 69 "Waypoint_29" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[.284950469331, -.169394328728, .660456967030, -1.179381585855, -1.206573510034, -1.222034237987], Waypoint_29_p)), a=1.2, v=0.1)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 70 "Stop tool" "noBreak"
    set_standard_digital_out(3, False)
    # end: URCap Program Node
    end_force_mode()
    stopl(5.0)
    $ 71 "MoveL"
    $ 72 "Direction: Tool Z-"
    global move_thread_flag_72=0
    thread move_thread_72():
      enter_critical
      move_thread_flag_72 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.05)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_72 = 2
      exit_critical
    end
    move_thread_flag_72 = 0
    move_thread_han_72 = run move_thread_72()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_72 > 1):
        join move_thread_han_72
        $ 73 "Until (distance)"
        break
      end
      sync()
    end
    $ 74 "Direction: CubeFront Z+"
    global move_thread_flag_74=0
    thread move_thread_74():
      enter_critical
      move_thread_flag_74 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.15)
      movel(towardsPos, a=1.2, v=0.25)
      move_thread_flag_74 = 2
      exit_critical
    end
    move_thread_flag_74 = 0
    move_thread_han_74 = run move_thread_74()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_74 > 1):
        join move_thread_han_74
        $ 75 "Until (distance)"
        break
      end
      sync()
    end
    $ 76 "MoveJ"
    $ 77 "Waypoint_32" "breakAfter"
    movej(get_inverse_kin(Waypoint_32_p, qnear=Waypoint_32_q), a=1.3962634015954636, v=1.0471975511965976)
  end
  def sprayRebate():
    $ 78 "sprayRebate" "noBreak"
    $ 79 "SprayRebate"
    $ 80 "MoveJ"
    $ 81 "Waypoint_14" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_14_p)), qnear=Waypoint_14_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 82 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 83 "MoveL"
    $ 84 "Waypoint_7" "breakAfter"
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_7_p)), a=1.2, v=0.1)
    $ 85 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 86 "Direction: CubeFront Z+"
    global move_thread_flag_86=0
    thread move_thread_86():
      enter_critical
      move_thread_flag_86 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_86 = 2
      exit_critical
    end
    move_thread_flag_86 = 0
    move_thread_han_86 = run move_thread_86()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_86 > 1):
        join move_thread_han_86
        $ 87 "Until (distance)"
        break
      end
      sync()
    end
    $ 88 "MoveJ"
    $ 89 "Waypoint_8" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_8_p)), qnear=Waypoint_8_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 90 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 91 "MoveL"
    $ 92 "Waypoint_9" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_9_p)), a=1.2, v=0.1)
    $ 93 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 94 "Direction: CubeFront Z+"
    global move_thread_flag_94=0
    thread move_thread_94():
      enter_critical
      move_thread_flag_94 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_94 = 2
      exit_critical
    end
    move_thread_flag_94 = 0
    move_thread_han_94 = run move_thread_94()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_94 > 1):
        join move_thread_han_94
        $ 95 "Until (distance)"
        break
      end
      sync()
    end
    $ 96 "MoveJ"
    $ 97 "Waypoint_11" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_11_p)), qnear=Waypoint_11_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 98 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 99 "MoveL"
    $ 100 "Waypoint_13" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_13_p)), a=1.2, v=0.1)
    $ 101 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 102 "Direction: CubeFront Z+"
    global move_thread_flag_102=0
    thread move_thread_102():
      enter_critical
      move_thread_flag_102 = 1
      local towardsPos=calculate_point_to_move_towards(p[-0.6555216255462147,-0.29387207677313937,0.132153542128245,1.1865363507504816,1.2077692688007782,1.2289777735514902], [0.0,0.0,1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_102 = 2
      exit_critical
    end
    move_thread_flag_102 = 0
    move_thread_han_102 = run move_thread_102()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_102 > 1):
        join move_thread_han_102
        $ 103 "Until (distance)"
        break
      end
      sync()
    end
  end
  def sprayFront():
    $ 104 "sprayFront" "noBreak"
    $ 105 "SprayFront"
    $ 106 "MoveJ"
    $ 107 "Waypoint_10" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_10_p)), qnear=Waypoint_10_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 108 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 109 "MoveL"
    $ 110 "Waypoint_12" "breakAfter"
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_12_p)), a=1.2, v=0.1)
    $ 111 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 112 "Direction: Tool Z-"
    global move_thread_flag_112=0
    thread move_thread_112():
      enter_critical
      move_thread_flag_112 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_112 = 2
      exit_critical
    end
    move_thread_flag_112 = 0
    move_thread_han_112 = run move_thread_112()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_112 > 1):
        join move_thread_han_112
        $ 113 "Until (distance)"
        break
      end
      sync()
    end
    $ 114 "MoveJ"
    $ 115 "Waypoint_21" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_21_p)), qnear=Waypoint_21_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 116 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 117 "MoveL"
    $ 118 "Waypoint_22" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_22_p)), a=1.2, v=0.1)
    $ 119 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 120 "Direction: Tool Z-"
    global move_thread_flag_120=0
    thread move_thread_120():
      enter_critical
      move_thread_flag_120 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_120 = 2
      exit_critical
    end
    move_thread_flag_120 = 0
    move_thread_han_120 = run move_thread_120()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_120 > 1):
        join move_thread_han_120
        $ 121 "Until (distance)"
        break
      end
      sync()
    end
    $ 122 "MoveJ"
    $ 123 "Waypoint_23" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_23_p)), qnear=Waypoint_23_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 124 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 125 "MoveL"
    $ 126 "Waypoint_24" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_24_p)), a=1.2, v=0.1)
    $ 127 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 128 "Direction: Tool Z-"
    global move_thread_flag_128=0
    thread move_thread_128():
      enter_critical
      move_thread_flag_128 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_128 = 2
      exit_critical
    end
    move_thread_flag_128 = 0
    move_thread_han_128 = run move_thread_128()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_128 > 1):
        join move_thread_han_128
        $ 129 "Until (distance)"
        break
      end
      sync()
    end
    $ 130 "MoveJ"
    $ 131 "Waypoint_38" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_38_p)), qnear=Waypoint_38_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 132 "Set SprayerOn=On"
    set_standard_digital_out(5, True)
    $ 133 "MoveL"
    $ 134 "Waypoint_25" "breakAfter"
    set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_25_p)), a=1.2, v=0.1)
    $ 135 "Set SprayerOn=Off"
    set_standard_digital_out(5, False)
    $ 136 "Direction: Tool Z-"
    global move_thread_flag_136=0
    thread move_thread_136():
      enter_critical
      move_thread_flag_136 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.1)
      movel(towardsPos, a=1.2, v=0.2)
      move_thread_flag_136 = 2
      exit_critical
    end
    move_thread_flag_136 = 0
    move_thread_han_136 = run move_thread_136()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_136 > 1):
        join move_thread_han_136
        $ 137 "Until (distance)"
        break
      end
      sync()
    end
  end
  def sandFront():
    $ 138 "sandFront" "noBreak"
    $ 139 "sandFront"
    $ 140 "Set"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    $ 141 "MoveL"
    $ 142 "Waypoint_2" "breakAfter"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_2_p)), a=1.2, v=0.25)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Zero FT Sensor
    $ 143 "Zero FT Sensor"
    
    rq_wait_ft_sensor_steady(2000)
    zero_ftsensor()
    sleep(0.1)
    # end: URCap Program Node
    $ 144 "Direction: Tool Z+"
    global move_thread_flag_144=0
    thread move_thread_144():
      enter_critical
      move_thread_flag_144 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,1.0], 1000.0)
      movel(towardsPos, a=1.2, v=0.05)
      move_thread_flag_144 = 2
      exit_critical
    end
    move_thread_flag_144 = 0
    move_thread_han_144 = run move_thread_144()
    while (True):
      local targetTcpDirection=get_target_tcp_speed()
      local stepsToRetract=tool_contact(direction=targetTcpDirection)
      if (stepsToRetract > 0):
        kill move_thread_han_144
        stopl(3.0)
        $ 145 "Until (tool_contact_detection)"
        break
      end
      sync()
    end
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 146 "Start tool"
    set_standard_digital_out(3, True)
    # end: URCap Program Node
    $ 147 "Wait: 1.0"
    sleep(1.0)
    $ 148 "MoveL"
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Zero FT Sensor
    $ 149 "Zero FT Sensor"
    
    zero_ftsensor()
    sleep(0.1)
    # end: URCap Program Node
    $ 150 "Force"
    sleep(0.02)
    zero_ftsensor()
    force_mode(tool_pose(), [0, 0, 1, 0, 0, 0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0], 2, [0.1, 0.1, 0.15, 0.3490658503988659, 0.3490658503988659, 0.3490658503988659])
    $ 151 "Waypoint_3" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_3_p)), a=1.2, v=0.12)
    $ 152 "Waypoint_4" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_4_p)), a=1.2, v=0.12)
    $ 153 "Waypoint_5" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_5_p)), a=1.2, v=0.12)
    $ 154 "Waypoint_6" "noBreak"
    set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
    movel(pose_trans(CubeFront, pose_trans(p[-.131847055554, -.113512547397, -.795239519450, .020655115358, .013310638043, -3.069721334155], Waypoint_6_p)), a=1.2, v=0.12)
    # begin: URCap Program Node
    #   Source: Robotiq_Copilot, 1.22.1.14215, Robotiq Inc.
    #   Type: Finishing Tool Control
    $ 155 "Stop tool" "noBreak"
    set_standard_digital_out(3, False)
    # end: URCap Program Node
    end_force_mode()
    stopl(5.0)
    $ 156 "Direction: Tool Z-"
    global move_thread_flag_156=0
    thread move_thread_156():
      enter_critical
      move_thread_flag_156 = 1
      local towardsPos=calculate_point_to_move_towards(get_forward_kin(), [0.0,0.0,-1.0], 0.025)
      movel(towardsPos, a=1.2, v=0.12)
      move_thread_flag_156 = 2
      exit_critical
    end
    move_thread_flag_156 = 0
    move_thread_han_156 = run move_thread_156()
    while (True):
      sleep(1.0E-10)
      if (move_thread_flag_156 > 1):
        join move_thread_han_156
        $ 157 "Until (distance)"
        break
      end
      sync()
    end
  end
  thread EventThread():
    while (True):
      if (get_standard_digital_in(2) ==   True  ):
        $ 14 "Set ClampOn=On"
        set_standard_digital_out(7, True)
        $ 15 "MoveJ"
        $ 16 "Waypoint_1" "breakAfter"
        set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
        movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.300286591152, -.149331691834, .650647942655, -1.193662016482, -1.190171861546, -1.213677846742], Waypoint_1_p)), qnear=Waypoint_1_q), a=1.3962634015954636, v=1.0471975511965976)
        $ 17 "Call sandFront"
        sandFront()
        $ 18 "Call sandFront"
        sandFront()
        $ 21 "MoveJ"
        $ 22 "Waypoint_1" "breakAfter"
        set_tcp(p[0.00318,0.11464,0.09820000000000001,-0.7853981633974483,0.0,0.0])
        movej(get_inverse_kin(pose_trans(CubeFront, pose_trans(p[.300286591152, -.149331691834, .650647942655, -1.193662016482, -1.190171861546, -1.213677846742], Waypoint_1_p)), qnear=Waypoint_1_q), a=1.3962634015954636, v=1.0471975511965976)
        $ 23 "Call sprayFront"
        sprayFront()
        $ 24 "Call sprayRebate"
        sprayRebate()
        $ 25 "Set ClampOn=Off"
        set_standard_digital_out(7, False)
        $ 26 "MoveJ"
        $ 27 "Waypoint_15" "breakAfter"
        set_tcp(p[0.020839023181949995,-0.027139950822234082,0.10599373590389219,0.12258870209179472,1.1769383890382668,2.869747076630172])
        movej(get_inverse_kin(Waypoint_15_p, qnear=Waypoint_15_q), a=1.3962634015954636, v=1.0471975511965976)
      end
      sync()
    end
  end
  eventThread = run EventThread()
  while (True):
    $ 1 "Robot Program"
    $ 2 "Set PinsUp=On"
    set_standard_digital_out(6, True)
    $ 3 "Wait: 0.01"
    sleep(0.01)
  end
end
